export function getAnalyticsData(dateRange: string, channelFilter: string) {
  return {
    kpis: {
      totalSent: 45678,
      totalSentChange: 12.3,
      deliveryRate: 98.3,
      deliveryRateChange: 0.8,
      industryDeliveryRate: 97.5,
      openRate: 38.7,
      openRateChange: 4.2,
      industryOpenRate: 35.2,
      clickRate: 9.2,
      clickRateChange: 1.8,
      industryClickRate: 8.5,
      conversions: 1234,
      conversionsChange: 23.4,
      revenue: 87456,
      revenueChange: 12345,
      roi: 847,
      roiChange: 145,
      unsubscribeRate: 0.8,
    },
    channels: [
      {
        name: "Email",
        sent: 32456,
        delivered: 31912,
        deliveryRate: 98.3,
        opens: 12456,
        openRate: 39.0,
        clicks: 3123,
        clickRate: 9.8,
        conversions: 890,
        conversionRate: 2.7,
        revenue: 62345,
        cost: "€0 (Free tier)",
        roi: "∞",
        status: "active",
      },
      {
        name: "SMS",
        sent: 13222,
        delivered: 13045,
        deliveryRate: 98.7,
        opens: null,
        openRate: null,
        clicks: 1567,
        clickRate: 12.0,
        conversions: 344,
        conversionRate: 2.6,
        revenue: 25111,
        cost: "€2,644.40",
        roi: "850%",
        status: "active",
      },
      {
        name: "In-App",
        sent: null,
        delivered: 8234,
        deliveryRate: null,
        opens: 8234,
        openRate: 68.0,
        clicks: 2456,
        clickRate: 29.8,
        conversions: 123,
        conversionRate: 1.5,
        revenue: 8900,
        cost: "€0 (Native)",
        roi: "∞",
        status: "active",
      },
      {
        name: "WhatsApp",
        sent: 0,
        delivered: 0,
        deliveryRate: null,
        opens: null,
        openRate: null,
        clicks: 0,
        clickRate: 0,
        conversions: 0,
        conversionRate: 0,
        revenue: 0,
        cost: "Not configured",
        roi: "-",
        status: "inactive",
      },
    ],
    topCampaigns: [
      {
        id: "1",
        name: "Flash Sale - 48hr",
        date: "Nov 5",
        channels: ["Email", "SMS"],
        sent: 5678,
        trend: "up",
        openRate: 48.2,
        openTrend: "up",
        openChange: 10,
        ctr: 15.6,
        ctrBenchmark: "↑ +6pp",
        convRate: 4.5,
        convTrend: "up",
        convChange: 2,
        revenue: 15678,
        revenueBenchmark: "↑ Best",
      },
      {
        id: "2",
        name: "Birthday Rewards (Nov)",
        date: "Nov 1-30",
        channels: ["SMS"],
        sent: 3456,
        trend: "up",
        openRate: 45.8,
        openTrend: "up",
        openChange: 8,
        ctr: 8.7,
        ctrBenchmark: "→ Avg",
        convRate: 5.2,
        convTrend: "up",
        convChange: 3,
        revenue: 12345,
        revenueBenchmark: "↑ High",
      },
      {
        id: "3",
        name: "Welcome Series",
        date: "Nov 15",
        channels: ["Email", "SMS"],
        sent: 1234,
        trend: "same",
        openRate: 42.3,
        openTrend: "up",
        openChange: 4,
        ctr: 8.7,
        ctrBenchmark: "→ Avg",
        convRate: 12.6,
        convTrend: "up",
        convChange: 10,
        revenue: 8900,
        revenueBenchmark: "→ Good",
      },
      {
        id: "4",
        name: "Weekend Brunch Special",
        date: "Nov 8",
        channels: ["SMS"],
        sent: 3456,
        trend: "up",
        openRate: 32.1,
        openTrend: "same",
        openChange: 0,
        ctr: 7.2,
        ctrBenchmark: "↓ -2pp",
        convRate: 2.8,
        convTrend: "same",
        convChange: 0,
        revenue: 7234,
        revenueBenchmark: "→ Good",
      },
      {
        id: "5",
        name: "Lapsed Customer Winback",
        date: "Nov 12",
        channels: ["Email"],
        sent: 892,
        trend: "same",
        openRate: 28.3,
        openTrend: "down",
        openChange: -4,
        ctr: 5.4,
        ctrBenchmark: "↓ -3pp",
        convRate: 3.1,
        convTrend: "same",
        convChange: 0,
        revenue: 5678,
        revenueBenchmark: "→ OK",
      },
    ],
    insights: [
      {
        type: "success",
        title: "Strong Performance Detected",
        description:
          "Your Flash Sale campaigns consistently outperform by 45%. Consider running similar campaigns more frequently.",
        impact: "High Impact",
        action: "Create Flash Sale Campaign",
      },
      {
        type: "opportunity",
        title: "Optimal Send Time Identified",
        description: "Your audience engages 32% more when emails are sent on Tuesday at 2:00 PM.",
        impact: "High Impact",
        action: "Apply to Future Campaigns",
      },
      {
        type: "opportunity",
        title: "Segment Opportunity",
        description:
          "High-value customers (LTV >€1000) have 3x higher conversion rates. Create a dedicated segment for premium offers.",
        impact: "High Impact",
        action: "Create VIP Segment",
      },
      {
        type: "warning",
        title: "Declining Engagement",
        description:
          "Open rates dropped 8% in the last 2 weeks. Your audience may be experiencing email fatigue. Consider reducing frequency or testing new content.",
        impact: "Action Needed",
        action: "View Recommendations",
      },
      {
        type: "action",
        title: "Revenue Attribution",
        description:
          "SMS campaigns generate 2.1x higher ROI than email. Allocate more budget to SMS for promotional campaigns.",
        impact: "High Impact",
        action: "View Full Analysis",
      },
    ],
  }
}
