import type { Subscription, Usage, PaymentMethod, Invoice, Plan } from "./types"

export const mockSubscription: Subscription = {
  id: "sub_1234567890",
  planId: "pro",
  planName: "Pro",
  status: "active",
  billing: {
    amount: 150,
    currency: "EUR",
    interval: "month",
    intervalCount: 1,
  },
  limits: {
    locations: 3,
    teamMembers: 10,
    orders: "unlimited",
    storage: 50,
    apiCalls: 100000,
    emailCredits: 1000,
  },
  features: [
    "Up to 3 locations",
    "Unlimited orders",
    "Online ordering",
    "10 team members",
    "Reservations",
    "Inventory management",
    "Advanced analytics",
    "Custom branding",
    "Priority support",
  ],
  currentPeriodStart: "2024-11-15",
  currentPeriodEnd: "2024-12-14",
  nextBillingDate: "2024-12-15",
  nextBillingAmount: 150,
  cancelAtPeriodEnd: false,
  createdAt: "2024-08-15",
  updatedAt: "2024-11-15",
}

export const mockUsage: Usage = {
  period: {
    start: "2024-11-15",
    end: "2024-12-14",
  },
  locations: {
    used: 3,
    limit: 3,
  },
  teamMembers: {
    used: 7,
    limit: 10,
  },
  orders: {
    used: 4234,
    limit: "unlimited",
  },
  storage: {
    used: 12.4,
    limit: 50,
  },
  apiCalls: {
    used: 89234,
    limit: 100000,
  },
  emailCredits: {
    used: 892,
    limit: 1000,
  },
}

export const mockPaymentMethods: PaymentMethod[] = [
  {
    id: "pm_1234567890",
    type: "card",
    card: {
      brand: "visa",
      last4: "4242",
      expMonth: 12,
      expYear: 2026,
      funding: "credit",
    },
    billingDetails: {
      name: "Sarah Johnson",
      email: "sarah@berrytap.com",
      phone: "+356 9123 4567",
      address: {
        line1: "123 Republic Street",
        line2: "Apartment 4B",
        city: "Valletta",
        postalCode: "VLT 1234",
        country: "MT",
      },
    },
    isDefault: true,
    addedBy: "user_123",
    addedByName: "Sarah Johnson",
    createdAt: "2024-10-01",
  },
  {
    id: "pm_0987654321",
    type: "card",
    card: {
      brand: "mastercard",
      last4: "8888",
      expMonth: 8,
      expYear: 2025,
      funding: "debit",
    },
    billingDetails: {
      name: "Michael Chen",
      email: "michael@berrytap.com",
      address: {
        line1: "456 Main Street",
        city: "Sliema",
        postalCode: "SLM 5678",
        country: "MT",
      },
    },
    isDefault: false,
    addedBy: "user_456",
    addedByName: "Michael Chen",
    createdAt: "2024-11-05",
  },
]

export const mockInvoices: Invoice[] = [
  {
    id: "inv_202411",
    number: "INV-2024-0015",
    date: "2024-11-15",
    dueDate: "2024-11-15",
    amount: 150,
    tax: 0,
    total: 150,
    currency: "EUR",
    status: "paid",
    description: "Pro Plan - Monthly",
    lineItems: [{ description: "Pro Plan (3 locations)", amount: 150 }],
    paidAt: "2024-11-15",
    paymentMethod: "Visa ••4242",
    pdfUrl: "/invoices/inv_202411.pdf",
  },
  {
    id: "inv_202410",
    number: "INV-2024-0014",
    date: "2024-10-15",
    dueDate: "2024-10-15",
    amount: 150,
    tax: 0,
    total: 150,
    currency: "EUR",
    status: "paid",
    description: "Pro Plan - Monthly",
    lineItems: [{ description: "Pro Plan (3 locations)", amount: 150 }],
    paidAt: "2024-10-15",
    paymentMethod: "Visa ••4242",
    pdfUrl: "/invoices/inv_202410.pdf",
  },
  {
    id: "inv_202409",
    number: "INV-2024-0013",
    date: "2024-09-15",
    dueDate: "2024-09-15",
    amount: 150,
    tax: 0,
    total: 150,
    currency: "EUR",
    status: "paid",
    description: "Pro Plan - Monthly",
    lineItems: [{ description: "Pro Plan (3 locations)", amount: 150 }],
    paidAt: "2024-09-15",
    paymentMethod: "Visa ••4242",
    pdfUrl: "/invoices/inv_202409.pdf",
  },
  {
    id: "inv_202408",
    number: "INV-2024-0012",
    date: "2024-08-20",
    dueDate: "2024-08-20",
    amount: 50,
    tax: 0,
    total: 50,
    currency: "EUR",
    status: "paid",
    description: "Additional Location",
    lineItems: [{ description: "Additional Location - One-time charge", amount: 50 }],
    paidAt: "2024-08-20",
    paymentMethod: "Visa ••4242",
    pdfUrl: "/invoices/inv_202408.pdf",
  },
]

export const mockPlans: Plan[] = [
  {
    id: "starter",
    name: "Starter",
    price: 49,
    interval: "month",
    description: "Perfect for single locations",
    features: ["1 location", "5 team members", "1K orders/month", "Basic analytics", "Email support"],
    limits: {
      locations: 1,
      teamMembers: 5,
      orders: 1000,
      storage: 10,
      apiCalls: 10000,
      emailCredits: 100,
    },
  },
  {
    id: "pro",
    name: "Pro",
    price: 150,
    interval: "month",
    description: "For growing restaurants",
    features: [
      "3 locations",
      "10 team members",
      "Unlimited orders",
      "Advanced analytics",
      "Custom branding",
      "Priority support",
      "API access",
      "Webhooks",
    ],
    limits: {
      locations: 3,
      teamMembers: 10,
      orders: "unlimited",
      storage: 50,
      apiCalls: 100000,
      emailCredits: 1000,
    },
    popular: true,
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: 500,
    interval: "month",
    description: "For large restaurant chains",
    features: [
      "Unlimited locations",
      "Unlimited team members",
      "Unlimited orders",
      "Custom analytics",
      "White label",
      "Dedicated support",
      "SLA guarantee",
      "Custom integrations",
    ],
    limits: {
      locations: "unlimited",
      teamMembers: "unlimited",
      orders: "unlimited",
      storage: 500,
      apiCalls: 1000000,
      emailCredits: 10000,
    },
  },
]
