// Menu Management Mock Data
import type { MenuItem, Category as SimpleCategory } from "@/types/menu-item"
import type { Category as DetailedCategory } from "@/types/category"

export const mockMenuCategories: SimpleCategory[] = [
  { id: "1", name: "Appetizers", emoji: "🥗", itemCount: 12, order: 1, isExpanded: true },
  { id: "2", name: "Pizzas", emoji: "🍕", itemCount: 9, order: 2, isExpanded: true },
  { id: "3", name: "Desserts", emoji: "🍰", itemCount: 7, order: 3, isExpanded: false },
  { id: "4", name: "Beverages", emoji: "🥤", itemCount: 15, order: 4, isExpanded: false },
]

export const mockMenus = [
  { id: "lunch", name: "Lunch Menu" },
  { id: "dinner", name: "Dinner Menu" },
  { id: "late-night", name: "Late Night Menu" },
  { id: "all-day", name: "All Day Menu" },
]

export const mockDetailedCategories: DetailedCategory[] = [
  {
    id: "1",
    name: "Appetizers",
    emoji: "🥗",
    description: "Start your meal with these delicious options",
    order: 1,
    itemCount: 12,
    menuIds: ["lunch", "dinner"],
    menuNames: ["Lunch Menu", "Dinner Menu"],
  },
  {
    id: "2",
    name: "Pizzas",
    emoji: "🍕",
    description: "Wood-fired artisan pizzas",
    order: 2,
    itemCount: 9,
    menuIds: ["lunch", "dinner", "late-night"],
    menuNames: ["Lunch Menu", "Dinner Menu", "Late Night Menu"],
  },
  {
    id: "3",
    name: "Desserts",
    emoji: "🍰",
    description: "Sweet treats to finish your meal",
    order: 3,
    itemCount: 7,
    menuIds: ["lunch", "dinner"],
    menuNames: ["Lunch Menu", "Dinner Menu"],
  },
  {
    id: "4",
    name: "Beverages",
    emoji: "🥤",
    description: "Hot and cold beverages",
    order: 4,
    itemCount: 15,
    menuIds: ["all-day"],
    menuNames: ["All Day Menu"],
  },
]

export const mockMenuItemsList: MenuItem[] = [
  {
    id: "1",
    name: "Caesar Salad",
    description: "Fresh romaine lettuce, parmesan cheese, croutons, Caesar dressing",
    price: 12.5,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400",
    status: "live",
    categories: ["Appetizers"],
    tags: ["Vegetarian", "Popular"],
    dietaryTags: ["vegetarian"],
    customizationGroups: ["dressing", "toppings", "protein"],
    availabilityMode: "menu-hours",
    category: "Appetizers",
    categoryId: "1",
    customizationCount: 3,
  },
  {
    id: "2",
    name: "Bruschetta",
    description: "Toasted bread topped with fresh tomatoes, basil, and olive oil",
    price: 9.99,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=400",
    status: "live",
    categories: ["Appetizers"],
    tags: ["Vegan", "Gluten-Free Option"],
    dietaryTags: ["vegan"],
    customizationGroups: [],
    availabilityMode: "menu-hours",
    category: "Appetizers",
    categoryId: "1",
  },
  {
    id: "3",
    name: "Margherita Pizza",
    description: "Classic pizza with tomato sauce, mozzarella, and fresh basil",
    price: 16.99,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400",
    status: "live",
    categories: ["Pizzas"],
    tags: ["Vegetarian", "Chef's Special"],
    dietaryTags: ["vegetarian"],
    customizationGroups: ["size", "toppings", "crust"],
    availabilityMode: "menu-hours",
    category: "Pizzas",
    categoryId: "2",
    customizationCount: 5,
  },
  {
    id: "4",
    name: "Pepperoni Pizza",
    description: "Loaded with pepperoni and mozzarella cheese",
    price: 18.99,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400",
    status: "live",
    categories: ["Pizzas"],
    tags: ["Popular"],
    dietaryTags: [],
    customizationGroups: ["size", "toppings", "crust"],
    availabilityMode: "menu-hours",
    category: "Pizzas",
    categoryId: "2",
    customizationCount: 4,
  },
  {
    id: "5",
    name: "Tiramisu",
    description: "Classic Italian dessert with coffee-soaked ladyfingers and mascarpone",
    price: 8.99,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400",
    status: "draft",
    categories: ["Desserts"],
    tags: ["Contains Alcohol"],
    dietaryTags: [],
    customizationGroups: [],
    availabilityMode: "menu-hours",
    category: "Desserts",
    categoryId: "3",
  },
  {
    id: "6",
    name: "Chocolate Lava Cake",
    description: "Warm chocolate cake with a molten center, served with vanilla ice cream",
    price: 9.99,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=400",
    status: "soldout",
    categories: ["Desserts"],
    tags: ["Vegetarian", "Popular"],
    dietaryTags: ["vegetarian"],
    customizationGroups: [],
    availabilityMode: "menu-hours",
    category: "Desserts",
    categoryId: "3",
    soldOutUntil: new Date("2025-01-20"),
  },
  {
    id: "7",
    name: "Caprese Salad",
    description: "Fresh mozzarella, tomatoes, and basil with balsamic glaze",
    price: 11.99,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1592417817098-8fd3d9eb14a5?w=400",
    status: "live",
    categories: ["Appetizers"],
    tags: ["Vegetarian", "Gluten-Free"],
    dietaryTags: ["vegetarian", "gluten-free"],
    customizationGroups: [],
    availabilityMode: "menu-hours",
    category: "Appetizers",
    categoryId: "1",
  },
  {
    id: "8",
    name: "Garlic Bread",
    description: "Toasted bread with garlic butter and herbs",
    price: 5.99,
    currency: "USD",
    status: "live",
    categories: ["Appetizers"],
    tags: ["Vegetarian"],
    dietaryTags: ["vegetarian"],
    customizationGroups: [],
    availabilityMode: "menu-hours",
    category: "Appetizers",
    categoryId: "1",
  },
  {
    id: "9",
    name: "BBQ Chicken Pizza",
    description: "BBQ sauce, grilled chicken, red onions, and cilantro",
    price: 19.99,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400",
    status: "live",
    categories: ["Pizzas"],
    tags: ["Spicy"],
    dietaryTags: [],
    customizationGroups: ["size", "toppings", "crust"],
    availabilityMode: "menu-hours",
    category: "Pizzas",
    categoryId: "2",
    customizationCount: 6,
  },
  {
    id: "10",
    name: "Veggie Supreme Pizza",
    description: "Bell peppers, mushrooms, onions, olives, and tomatoes",
    price: 17.99,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1511689660979-10d2b1aada49?w=400",
    status: "hidden",
    categories: ["Pizzas"],
    tags: ["Vegetarian", "Vegan Option"],
    dietaryTags: ["vegetarian"],
    customizationGroups: ["size", "toppings", "crust"],
    availabilityMode: "menu-hours",
    category: "Pizzas",
    categoryId: "2",
  },
  {
    id: "11",
    name: "Panna Cotta",
    description: "Creamy Italian dessert with berry compote",
    price: 7.99,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400",
    status: "live",
    categories: ["Desserts"],
    tags: ["Vegetarian", "Gluten-Free"],
    dietaryTags: ["vegetarian", "gluten-free"],
    customizationGroups: [],
    availabilityMode: "menu-hours",
    category: "Desserts",
    categoryId: "3",
  },
  {
    id: "12",
    name: "Iced Coffee",
    description: "Cold brew coffee served over ice",
    price: 4.99,
    currency: "USD",
    status: "live",
    categories: ["Beverages"],
    tags: ["Vegan", "Contains Caffeine"],
    dietaryTags: ["vegan"],
    customizationGroups: ["milk", "sweetener", "size"],
    availabilityMode: "menu-hours",
    category: "Beverages",
    categoryId: "4",
  },
  {
    id: "13",
    name: "Mystery Dish",
    description: "A special dish that needs to be categorized",
    price: 15.99,
    currency: "USD",
    status: "draft",
    categories: [],
    tags: ["New"],
    dietaryTags: [],
    customizationGroups: [],
    availabilityMode: "menu-hours",
    category: "",
    categoryId: "",
  },
]






export const mockOrders = [
  { id: "1234", table: "5", total: 45.5, status: "Preparing", items: 3, time: "10 min ago" },
  { id: "1235", table: "2", total: 32.0, status: "Pending", items: 2, time: "5 min ago" },
  { id: "1236", table: "8", total: 78.25, status: "Ready", items: 5, time: "2 min ago" },
  { id: "1237", table: "12", total: 56.0, status: "Preparing", items: 4, time: "15 min ago" },
  { id: "1238", table: "3", total: 23.5, status: "Completed", items: 2, time: "30 min ago" },
]

export const mockRevenue = [
  { time: "10:00", value: 120 },
  { time: "10:30", value: 135 },
  { time: "11:00", value: 160 },
  { time: "11:30", value: 195 },
  { time: "12:00", value: 280 },
  { time: "12:30", value: 310 },
  { time: "13:00", value: 340 },
  { time: "13:30", value: 295 },
  { time: "14:00", value: 220 },
  { time: "14:30", value: 205 },
  { time: "15:00", value: 180 },
  { time: "15:30", value: 165 },
  { time: "16:00", value: 150 },
  { time: "16:30", value: 170 },
  { time: "17:00", value: 200 },
  { time: "17:30", value: 265 },
  { time: "18:00", value: 380 },
  { time: "18:30", value: 405 },
  { time: "19:00", value: 420 },
  { time: "19:30", value: 395 },
  { time: "20:00", value: 360 },
  { time: "20:30", value: 305 },
  { time: "21:00", value: 240 },
  { time: "21:30", value: 195 },
]

export const mockTables = [
  // Main Hall
  {
    id: "T1",
    number: "1",
    capacity: 2,
    status: "available" as const,
    section: "Main Hall",
    shape: "square" as const,
    lastCleaned: "15 min ago",
    condition: "excellent",
  },
  {
    id: "T2",
    number: "2",
    capacity: 4,
    status: "occupied" as const,
    section: "Main Hall",
    shape: "round" as const,
    guests: 4,
    server: "John Smith",
    serverId: "S1",
    duration: 32,
    orderId: "ORD-1235",
    seatedAt: "6:23 PM",
    urgency: "normal" as const,
  },
  {
    id: "T3",
    number: "3",
    capacity: 4,
    status: "reserved" as const,
    section: "Main Hall",
    shape: "square" as const,
    reservationTime: "7:00 PM",
    reservationId: "R1",
    guestName: "Sarah Johnson",
    partySize: 4,
    timeUntil: "5 min",
    lastCleaned: "2 hours ago",
  },
  {
    id: "T4",
    number: "4",
    capacity: 6,
    status: "available" as const,
    section: "Main Hall",
    shape: "round" as const,
    lastCleaned: "30 min ago",
    condition: "good",
  },
  {
    id: "T5",
    number: "5",
    capacity: 2,
    status: "occupied" as const,
    section: "Main Hall",
    shape: "square" as const,
    guests: 2,
    server: "Maria Garcia",
    serverId: "S2",
    duration: 18,
    orderId: "ORD-1234",
    seatedAt: "6:37 PM",
    urgency: "normal" as const,
  },
  {
    id: "T6",
    number: "6",
    capacity: 8,
    status: "cleaning" as const,
    section: "Main Hall",
    shape: "round" as const,
    cleanedBy: "Staff",
    cleaningStarted: "8 min ago",
  },
  {
    id: "T7",
    number: "7",
    capacity: 4,
    status: "occupied" as const,
    section: "Main Hall",
    shape: "square" as const,
    guests: 3,
    server: "John Smith",
    serverId: "S1",
    duration: 65,
    orderId: "ORD-1239",
    seatedAt: "5:50 PM",
    urgency: "warning" as const,
  },
  {
    id: "T8",
    number: "8",
    capacity: 4,
    status: "occupied" as const,
    section: "Main Hall",
    shape: "round" as const,
    guests: 4,
    server: "David Lee",
    serverId: "S3",
    duration: 45,
    orderId: "ORD-1236",
    seatedAt: "6:10 PM",
    urgency: "normal" as const,
  },
  {
    id: "T9",
    number: "9",
    capacity: 2,
    status: "available" as const,
    section: "Main Hall",
    shape: "square" as const,
    lastCleaned: "10 min ago",
    condition: "excellent",
  },
  {
    id: "T10",
    number: "10",
    capacity: 6,
    status: "reserved" as const,
    section: "Main Hall",
    shape: "round" as const,
    reservationTime: "7:30 PM",
    reservationId: "R2",
    guestName: "Michael Chen",
    partySize: 2,
    timeUntil: "35 min",
    lastCleaned: "1 hour ago",
  },
  // Patio
  {
    id: "T11",
    number: "11",
    capacity: 4,
    status: "available" as const,
    section: "Patio",
    shape: "square" as const,
    lastCleaned: "20 min ago",
    condition: "good",
  },
  {
    id: "T12",
    number: "12",
    capacity: 6,
    status: "occupied" as const,
    section: "Patio",
    shape: "round" as const,
    guests: 5,
    server: "Maria Garcia",
    serverId: "S2",
    duration: 28,
    orderId: "ORD-1237",
    seatedAt: "6:27 PM",
    urgency: "normal" as const,
  },
  {
    id: "T13",
    number: "13",
    capacity: 4,
    status: "occupied" as const,
    section: "Patio",
    shape: "square" as const,
    guests: 4,
    server: "John Smith",
    serverId: "S1",
    duration: 92,
    orderId: "ORD-1230",
    seatedAt: "5:23 PM",
    urgency: "delayed" as const,
  },
  {
    id: "T14",
    number: "14",
    capacity: 2,
    status: "cleaning" as const,
    section: "Patio",
    shape: "square" as const,
    cleanedBy: "Staff",
    cleaningStarted: "3 min ago",
  },
  {
    id: "T15",
    number: "15",
    capacity: 4,
    status: "occupied" as const,
    section: "Patio",
    shape: "round" as const,
    guests: 2,
    server: "David Lee",
    serverId: "S3",
    duration: 22,
    orderId: "ORD-1240",
    seatedAt: "6:33 PM",
    urgency: "normal" as const,
  },
  {
    id: "T16",
    number: "16",
    capacity: 6,
    status: "reserved" as const,
    section: "Patio",
    shape: "round" as const,
    reservationTime: "8:00 PM",
    reservationId: "R3",
    guestName: "Emily Davis",
    partySize: 6,
    timeUntil: "1 hour 5 min",
    lastCleaned: "45 min ago",
  },
  // Private
  {
    id: "T17",
    number: "17",
    capacity: 8,
    status: "available" as const,
    section: "Private",
    shape: "round" as const,
    lastCleaned: "1 hour ago",
    condition: "excellent",
  },
  {
    id: "T18",
    number: "18",
    capacity: 10,
    status: "reserved" as const,
    section: "Private",
    shape: "round" as const,
    reservationTime: "8:30 PM",
    reservationId: "R5",
    guestName: "Corporate Event",
    partySize: 10,
    timeUntil: "1 hour 35 min",
    lastCleaned: "2 hours ago",
    notes: "VIP - Special setup required",
  },
  {
    id: "T19",
    number: "19",
    capacity: 6,
    status: "occupied" as const,
    section: "Private",
    shape: "square" as const,
    guests: 6,
    server: "Maria Garcia",
    serverId: "S2",
    duration: 38,
    orderId: "ORD-1242",
    seatedAt: "6:17 PM",
    urgency: "normal" as const,
  },
  {
    id: "T20",
    number: "20",
    capacity: 4,
    status: "available" as const,
    section: "Private",
    shape: "square" as const,
    lastCleaned: "25 min ago",
    condition: "good",
  },
]

export const mockReservations = [
  {
    id: "RSV-2847",
    code: "RSV-2847",
    guestName: "Anna K.",
    fullName: "Anna Kowalski",
    partySize: 4,
    children: 0,
    date: "2025-01-10",
    time: "7:30 PM",
    endTime: "9:00 PM",
    duration: 90,
    status: "reserved" as const,
    phone: "(555) 123-4567",
    email: "anna.k@email.com",
    table: "12",
    tableId: "T12",
    zone: "Main Hall",
    staff: "John Smith",
    staffId: "S1",
    source: "Website",
    notes: "Window seating preferred",
    specialRequests: "Birthday celebration - need cake service",
    dietaryNeeds: ["Vegetarian", "Gluten-free"],
    tags: ["VIP", "Birthday"],
    isVIP: true,
    isRegular: true,
    visitCount: 12,
    loyaltyTier: "Gold",
    graceMinutes: 15,
    minutesUntil: 15,
    urgency: "arriving-soon" as const,
    linkedOrderId: null,
    customerProfile: {
      totalVisits: 12,
      lastVisit: "2024-12-28",
      avgSpend: 145.0,
      favoriteItems: ["Grilled Salmon", "Caesar Salad"],
      preferences: "Window seating, quiet area",
      noShowCount: 0,
      cancelCount: 1,
    },
    timeline: [
      { event: "Reservation created", time: "2025-01-08 10:30 AM", user: "Anna K.", avatar: "AK" },
      { event: "Confirmed via email", time: "2025-01-08 10:32 AM", user: "System", avatar: "S" },
      { event: "Table assigned", time: "2025-01-10 6:00 PM", user: "John Smith", avatar: "JS" },
    ],
  },
  {
    id: "RSV-2848",
    code: "RSV-2848",
    guestName: "Michael Chen",
    fullName: "Michael Chen",
    partySize: 2,
    children: 0,
    date: "2025-01-10",
    time: "8:00 PM",
    endTime: "9:30 PM",
    duration: 90,
    status: "confirmed" as const,
    phone: "(555) 234-5678",
    email: "m.chen@email.com",
    table: "5",
    tableId: "T5",
    zone: "Main Hall",
    staff: "Maria Garcia",
    staffId: "S2",
    source: "Phone",
    notes: "",
    specialRequests: "",
    dietaryNeeds: [],
    tags: [],
    isVIP: false,
    isRegular: false,
    visitCount: 3,
    loyaltyTier: "Silver",
    graceMinutes: 15,
    minutesUntil: 45,
    urgency: "normal" as const,
    linkedOrderId: null,
    customerProfile: {
      totalVisits: 3,
      lastVisit: "2024-12-15",
      avgSpend: 85.0,
      favoriteItems: ["Ribeye Steak"],
      preferences: "",
      noShowCount: 0,
      cancelCount: 0,
    },
    timeline: [
      { event: "Reservation created", time: "2025-01-09 2:15 PM", user: "Phone", avatar: "P" },
      { event: "Confirmed via SMS", time: "2025-01-09 2:20 PM", user: "System", avatar: "S" },
    ],
  },
  {
    id: "RSV-2849",
    code: "RSV-2849",
    guestName: "Sarah Johnson",
    fullName: "Sarah Johnson",
    partySize: 6,
    children: 2,
    date: "2025-01-10",
    time: "6:30 PM",
    endTime: "8:30 PM",
    duration: 120,
    status: "seated" as const,
    phone: "(555) 345-6789",
    email: "sarah.j@email.com",
    table: "16",
    tableId: "T16",
    zone: "Patio",
    staff: "David Lee",
    staffId: "S3",
    source: "Walk-in",
    notes: "High chair needed",
    specialRequests: "Kids menu required",
    dietaryNeeds: ["Nut allergy"],
    tags: ["Kids"],
    isVIP: false,
    isRegular: true,
    visitCount: 8,
    loyaltyTier: "Silver",
    graceMinutes: 15,
    minutesUntil: -25,
    urgency: "seated" as const,
    linkedOrderId: "ORD-1245",
    customerProfile: {
      totalVisits: 8,
      lastVisit: "2025-01-03",
      avgSpend: 120.0,
      favoriteItems: ["Margherita Pizza", "Tiramisu"],
      preferences: "Family-friendly area",
      noShowCount: 0,
      cancelCount: 0,
    },
    timeline: [
      { event: "Walk-in arrival", time: "2025-01-10 6:30 PM", user: "David Lee", avatar: "DL" },
      { event: "Table assigned", time: "2025-01-10 6:31 PM", user: "David Lee", avatar: "DL" },
      { event: "Seated", time: "2025-01-10 6:32 PM", user: "David Lee", avatar: "DL" },
      { event: "Order created", time: "2025-01-10 6:35 PM", user: "David Lee", avatar: "DL" },
    ],
  },
  {
    id: "RSV-2850",
    code: "RSV-2850",
    guestName: "Emily Davis",
    fullName: "Emily Davis",
    partySize: 4,
    children: 0,
    date: "2025-01-10",
    time: "7:00 PM",
    endTime: "8:30 PM",
    duration: 90,
    status: "completed" as const,
    phone: "(555) 456-7890",
    email: "emily.d@email.com",
    table: "8",
    tableId: "T8",
    zone: "Main Hall",
    staff: "John Smith",
    staffId: "S1",
    source: "App",
    notes: "",
    specialRequests: "Anniversary - complimentary dessert",
    dietaryNeeds: [],
    tags: ["Anniversary"],
    isVIP: false,
    isRegular: false,
    visitCount: 2,
    loyaltyTier: "Bronze",
    graceMinutes: 15,
    minutesUntil: -55,
    urgency: "completed" as const,
    linkedOrderId: "ORD-1244",
    customerProfile: {
      totalVisits: 2,
      lastVisit: "2024-11-20",
      avgSpend: 95.0,
      favoriteItems: ["Grilled Salmon"],
      preferences: "",
      noShowCount: 0,
      cancelCount: 0,
    },
    timeline: [
      { event: "Reservation created", time: "2025-01-07 9:00 AM", user: "App", avatar: "A" },
      { event: "Confirmed", time: "2025-01-07 9:01 AM", user: "System", avatar: "S" },
      { event: "Arrived", time: "2025-01-10 6:58 PM", user: "John Smith", avatar: "JS" },
      { event: "Seated", time: "2025-01-10 7:00 PM", user: "John Smith", avatar: "JS" },
      { event: "Order completed", time: "2025-01-10 7:55 PM", user: "John Smith", avatar: "JS" },
    ],
  },
  {
    id: "RSV-2851",
    code: "RSV-2851",
    guestName: "James Wilson",
    fullName: "James Wilson",
    partySize: 8,
    children: 0,
    date: "2025-01-10",
    time: "6:00 PM",
    endTime: "7:00 PM",
    duration: 60,
    status: "late" as const,
    phone: "(555) 567-8901",
    email: "j.wilson@email.com",
    table: "18",
    tableId: "T18",
    zone: "Private",
    staff: "Maria Garcia",
    staffId: "S2",
    source: "Phone",
    notes: "Corporate dinner",
    specialRequests: "Private room required",
    dietaryNeeds: [],
    tags: ["Corporate"],
    isVIP: true,
    isRegular: false,
    visitCount: 1,
    loyaltyTier: "Bronze",
    graceMinutes: 15,
    minutesUntil: -55,
    graceLeft: 10,
    urgency: "late" as const,
    linkedOrderId: null,
    customerProfile: {
      totalVisits: 1,
      lastVisit: null,
      avgSpend: 0,
      favoriteItems: [],
      preferences: "",
      noShowCount: 0,
      cancelCount: 0,
    },
    timeline: [
      { event: "Reservation created", time: "2025-01-05 3:00 PM", user: "Phone", avatar: "P" },
      { event: "Confirmed", time: "2025-01-05 3:05 PM", user: "System", avatar: "S" },
      { event: "Reminder sent", time: "2025-01-10 10:00 AM", user: "System", avatar: "S" },
    ],
  },
  {
    id: "RSV-2852",
    code: "RSV-2852",
    guestName: "Lisa Anderson",
    fullName: "Lisa Anderson",
    partySize: 3,
    children: 1,
    date: "2025-01-10",
    time: "8:30 PM",
    endTime: "10:00 PM",
    duration: 90,
    status: "confirmed" as const,
    phone: "(555) 678-9012",
    email: "lisa.a@email.com",
    table: "10",
    tableId: "T10",
    zone: "Main Hall",
    staff: "David Lee",
    staffId: "S3",
    source: "Website",
    notes: "",
    specialRequests: "",
    dietaryNeeds: [],
    tags: [],
    isVIP: false,
    isRegular: false,
    visitCount: 1,
    loyaltyTier: "Bronze",
    graceMinutes: 15,
    minutesUntil: 75,
    urgency: "normal" as const,
    linkedOrderId: null,
    customerProfile: {
      totalVisits: 1,
      lastVisit: null,
      avgSpend: 0,
      favoriteItems: [],
      preferences: "",
      noShowCount: 0,
      cancelCount: 0,
    },
    timeline: [
      { event: "Reservation created", time: "2025-01-09 11:00 AM", user: "Website", avatar: "W" },
      { event: "Confirmed", time: "2025-01-09 11:02 AM", user: "System", avatar: "S" },
    ],
  },
  {
    id: "RSV-2853",
    code: "RSV-2853",
    guestName: "Robert Taylor",
    fullName: "Robert Taylor",
    partySize: 2,
    children: 0,
    date: "2025-01-09",
    time: "7:30 PM",
    endTime: "9:00 PM",
    duration: 90,
    status: "cancelled" as const,
    phone: "(555) 789-0123",
    email: "r.taylor@email.com",
    table: null,
    tableId: null,
    zone: null,
    staff: null,
    staffId: null,
    source: "Phone",
    notes: "",
    specialRequests: "",
    dietaryNeeds: [],
    tags: [],
    isVIP: false,
    isRegular: false,
    visitCount: 2,
    loyaltyTier: "Bronze",
    graceMinutes: 15,
    minutesUntil: null,
    urgency: "cancelled" as const,
    linkedOrderId: null,
    customerProfile: {
      totalVisits: 2,
      lastVisit: "2024-10-15",
      avgSpend: 75.0,
      favoriteItems: [],
      preferences: "",
      noShowCount: 0,
      cancelCount: 1,
    },
    timeline: [
      { event: "Reservation created", time: "2025-01-07 4:00 PM", user: "Phone", avatar: "P" },
      { event: "Confirmed", time: "2025-01-07 4:05 PM", user: "System", avatar: "S" },
      { event: "Cancelled by guest", time: "2025-01-09 5:00 PM", user: "Phone", avatar: "P" },
    ],
  },
  {
    id: "RSV-2854",
    code: "RSV-2854",
    guestName: "Amanda White",
    fullName: "Amanda White",
    partySize: 5,
    children: 0,
    date: "2025-01-09",
    time: "6:30 PM",
    endTime: "8:00 PM",
    duration: 90,
    status: "noShow" as const,
    phone: "(555) 890-1234",
    email: "a.white@email.com",
    table: "14",
    tableId: "T14",
    zone: "Patio",
    staff: "John Smith",
    staffId: "S1",
    source: "Website",
    notes: "",
    specialRequests: "",
    dietaryNeeds: [],
    tags: [],
    isVIP: false,
    isRegular: false,
    visitCount: 1,
    loyaltyTier: "Bronze",
    graceMinutes: 15,
    minutesUntil: null,
    urgency: "no-show" as const,
    linkedOrderId: null,
    customerProfile: {
      totalVisits: 1,
      lastVisit: "2024-12-01",
      avgSpend: 60.0,
      favoriteItems: [],
      preferences: "",
      noShowCount: 1,
      cancelCount: 0,
    },
    timeline: [
      { event: "Reservation created", time: "2025-01-08 2:00 PM", user: "Website", avatar: "W" },
      { event: "Confirmed", time: "2025-01-08 2:02 PM", user: "System", avatar: "S" },
      { event: "Reminder sent", time: "2025-01-09 10:00 AM", user: "System", avatar: "S" },
      { event: "Marked as no-show", time: "2025-01-09 6:50 PM", user: "John Smith", avatar: "JS" },
    ],
  },
  {
    id: "RSV-2855",
    code: "RSV-2855",
    guestName: "David Brown",
    fullName: "David Brown",
    partySize: 10,
    children: 0,
    date: "2025-01-11",
    time: "7:00 PM",
    endTime: "9:30 PM",
    duration: 150,
    status: "confirmed" as const,
    phone: "(555) 901-2345",
    email: "d.brown@email.com",
    table: "18",
    tableId: "T18",
    zone: "Private",
    staff: "Maria Garcia",
    staffId: "S2",
    source: "Phone",
    notes: "Birthday party - need decorations",
    specialRequests: "Cake service at 8:30 PM",
    dietaryNeeds: ["Vegan", "Dairy-free"],
    tags: ["Birthday", "Large Party"],
    isVIP: false,
    isRegular: true,
    visitCount: 6,
    loyaltyTier: "Silver",
    graceMinutes: 15,
    minutesUntil: 1495,
    urgency: "normal" as const,
    linkedOrderId: null,
    customerProfile: {
      totalVisits: 6,
      lastVisit: "2024-12-20",
      avgSpend: 180.0,
      favoriteItems: ["Margherita Pizza", "House Salad"],
      preferences: "Private room for groups",
      noShowCount: 0,
      cancelCount: 0,
    },
    timeline: [
      { event: "Reservation created", time: "2025-01-06 1:00 PM", user: "Phone", avatar: "P" },
      { event: "Confirmed", time: "2025-01-06 1:05 PM", user: "System", avatar: "S" },
      { event: "Special requests noted", time: "2025-01-06 1:10 PM", user: "Maria Garcia", avatar: "MG" },
    ],
  },
  {
    id: "RSV-2856",
    code: "RSV-2856",
    guestName: "Jennifer Martinez",
    fullName: "Jennifer Martinez",
    partySize: 4,
    children: 0,
    date: "2025-01-11",
    time: "6:30 PM",
    endTime: "8:00 PM",
    duration: 90,
    status: "confirmed" as const,
    phone: "(555) 012-3456",
    email: "j.martinez@email.com",
    table: "7",
    tableId: "T7",
    zone: "Main Hall",
    staff: "John Smith",
    staffId: "S1",
    source: "App",
    notes: "",
    specialRequests: "",
    dietaryNeeds: [],
    tags: [],
    isVIP: false,
    isRegular: false,
    visitCount: 1,
    loyaltyTier: "Bronze",
    graceMinutes: 15,
    minutesUntil: 1465,
    urgency: "normal" as const,
    linkedOrderId: null,
    customerProfile: {
      totalVisits: 1,
      lastVisit: null,
      avgSpend: 0,
      favoriteItems: [],
      preferences: "",
      noShowCount: 0,
      cancelCount: 0,
    },
    timeline: [
      { event: "Reservation created", time: "2025-01-10 9:00 AM", user: "App", avatar: "A" },
      { event: "Confirmed", time: "2025-01-10 9:01 AM", user: "System", avatar: "S" },
    ],
  },
  {
    id: "RSV-2857",
    code: "RSV-2857",
    guestName: "Christopher Lee",
    fullName: "Christopher Lee",
    partySize: 2,
    children: 0,
    date: "2025-01-11",
    time: "8:00 PM",
    endTime: "9:30 PM",
    duration: 90,
    status: "waitlist" as const,
    phone: "(555) 123-4568",
    email: "c.lee@email.com",
    table: null,
    tableId: null,
    zone: null,
    staff: null,
    staffId: null,
    source: "Phone",
    notes: "Willing to wait for table",
    specialRequests: "",
    dietaryNeeds: [],
    tags: ["Waitlist"],
    isVIP: false,
    isRegular: false,
    visitCount: 3,
    loyaltyTier: "Bronze",
    graceMinutes: 15,
    minutesUntil: 1555,
    urgency: "waitlist" as const,
    linkedOrderId: null,
    customerProfile: {
      totalVisits: 3,
      lastVisit: "2024-12-10",
      avgSpend: 70.0,
      favoriteItems: ["Ribeye Steak"],
      preferences: "",
      noShowCount: 0,
      cancelCount: 0,
    },
    timeline: [{ event: "Added to waitlist", time: "2025-01-10 3:00 PM", user: "Phone", avatar: "P" }],
  },
  {
    id: "RSV-2858",
    code: "RSV-2858",
    guestName: "Patricia Garcia",
    fullName: "Patricia Garcia",
    partySize: 6,
    children: 2,
    date: "2025-01-10",
    time: "7:45 PM",
    endTime: "9:15 PM",
    duration: 90,
    status: "confirmed" as const,
    phone: "(555) 234-5679",
    email: "p.garcia@email.com",
    table: "17",
    tableId: "T17",
    zone: "Private",
    staff: "David Lee",
    staffId: "S3",
    source: "Website",
    notes: "Booster seat needed",
    specialRequests: "Kids menu",
    dietaryNeeds: [],
    tags: ["Kids"],
    isVIP: false,
    isRegular: true,
    visitCount: 5,
    loyaltyTier: "Silver",
    graceMinutes: 15,
    minutesUntil: 30,
    urgency: "normal" as const,
    linkedOrderId: null,
    customerProfile: {
      totalVisits: 5,
      lastVisit: "2024-12-28",
      avgSpend: 110.0,
      favoriteItems: ["Margherita Pizza", "Caesar Salad"],
      preferences: "Family-friendly seating",
      noShowCount: 0,
      cancelCount: 0,
    },
    timeline: [
      { event: "Reservation created", time: "2025-01-08 5:00 PM", user: "Website", avatar: "W" },
      { event: "Confirmed", time: "2025-01-08 5:02 PM", user: "System", avatar: "S" },
    ],
  },
]

export const mockWaitlist = [
  {
    id: "W1",
    guestName: "Christopher Lee",
    partySize: 2,
    phone: "(555) 123-4568",
    addedAt: "3:00 PM",
    waitTime: "25 min",
    notes: "Willing to wait",
  },
  {
    id: "W2",
    guestName: "Karen Smith",
    partySize: 4,
    phone: "(555) 234-5670",
    addedAt: "3:15 PM",
    waitTime: "10 min",
    notes: "",
  },
]

export const mockMenuItems = [
  { id: "M1", name: "Caesar Salad", category: "Appetizers", price: 12.99, available: true },
  { id: "M2", name: "Grilled Salmon", category: "Entrees", price: 28.99, available: true },
  { id: "M3", name: "Ribeye Steak", category: "Entrees", price: 42.99, available: true },
  { id: "M4", name: "Margherita Pizza", category: "Entrees", price: 18.99, available: true },
  { id: "M5", name: "Chocolate Lava Cake", category: "Desserts", price: 9.99, available: false },
  { id: "M6", name: "Tiramisu", category: "Desserts", price: 8.99, available: true },
]

export const mockKPIs = [
  { label: "Today's Revenue", value: "$3,240", change: "+12.5%", trend: "up" as const },
  { label: "Active Orders", value: "8", change: "+2", trend: "up" as const },
  { label: "Table Occupancy", value: "65%", change: "-5%", trend: "down" as const },
  { label: "Avg. Wait Time", value: "12 min", change: "-3 min", trend: "up" as const },
]

export const mockActivityFeed = [
  {
    id: "A1",
    type: "order" as const,
    message: "New order #1239 placed for Table 7",
    time: "2 min ago",
    icon: "shopping-cart",
  },
  {
    id: "A2",
    type: "reservation" as const,
    message: "Reservation confirmed for Sarah Johnson (4 guests)",
    time: "5 min ago",
    icon: "calendar",
  },
  {
    id: "A3",
    type: "payment" as const,
    message: "Payment received for Order #1238 - $23.50",
    time: "8 min ago",
    icon: "credit-card",
  },
  {
    id: "A4",
    type: "order" as const,
    message: "Order #1236 marked as ready",
    time: "12 min ago",
    icon: "check-circle",
  },
  {
    id: "A5",
    type: "staff" as const,
    message: "Server John clocked in",
    time: "15 min ago",
    icon: "user",
  },
  {
    id: "A6",
    type: "reservation" as const,
    message: "Emily Davis party arrived and seated at Table 8",
    time: "18 min ago",
    icon: "users",
  },
  {
    id: "A7",
    type: "order" as const,
    message: "Order #1234 completed",
    time: "22 min ago",
    icon: "check-circle",
  },
  {
    id: "A8",
    type: "payment" as const,
    message: "Payment received for Order #1237 - $56.00",
    time: "25 min ago",
    icon: "credit-card",
  },
  {
    id: "A9",
    type: "staff" as const,
    message: "Chef Maria started shift",
    time: "30 min ago",
    icon: "chef-hat",
  },
  {
    id: "A10",
    type: "reservation" as const,
    message: "New reservation request from Michael Chen",
    time: "35 min ago",
    icon: "calendar",
  },
]

export const mockOrdersByHour = [
  { hour: "9 AM", orders: 5 },
  { hour: "10 AM", orders: 8 },
  { hour: "11 AM", orders: 12 },
  { hour: "12 PM", orders: 28 },
  { hour: "1 PM", orders: 32 },
  { hour: "2 PM", orders: 18 },
  { hour: "3 PM", orders: 10 },
  { hour: "4 PM", orders: 7 },
  { hour: "5 PM", orders: 15 },
  { hour: "6 PM", orders: 35 },
  { hour: "7 PM", orders: 42 },
  { hour: "8 PM", orders: 38 },
]

export const mockTableUtilization = [
  { name: "Occupied", value: 12, fill: "hsl(var(--chart-1))" },
  { name: "Reserved", value: 5, fill: "hsl(var(--chart-2))" },
  { name: "Available", value: 8, fill: "hsl(var(--chart-3))" },
]

export const mockSparklineData = [
  { value: 120 },
  { value: 145 },
  { value: 132 },
  { value: 158 },
  { value: 142 },
  { value: 165 },
  { value: 178 },
  { value: 185 },
  { value: 172 },
  { value: 195 },
]

export const mockAlerts = [
  {
    id: "alert-1",
    variant: "destructive" as const,
    message: "3 orders delayed over 20 minutes",
    action: { label: "View Now", onClick: () => console.log("[v0] View delayed orders") },
  },
  {
    id: "alert-2",
    variant: "warning" as const,
    message: "5 menu items need restocking",
    action: { label: "Manage Inventory", onClick: () => console.log("[v0] Manage inventory") },
  },
  {
    id: "alert-3",
    variant: "success" as const,
    message: "New 5-star review posted by Sarah J.",
    action: { label: "Read Review", onClick: () => console.log("[v0] Read review") },
  },
]

export const mockStaff = [
  { id: "S1", name: "John Smith", role: "Server", status: "active", tables: 4 },
  { id: "S2", name: "Maria Garcia", role: "Chef", status: "active", orders: 8 },
  { id: "S3", name: "David Lee", role: "Server", status: "break", tables: 0 },
]

export const mockDetailedOrders = [
  {
    id: "ORD-1234",
    table: "5",
    customer: "Sarah Johnson",
    items: [
      { name: "Caesar Salad", qty: 1, price: 12.99, mods: "No croutons" },
      { name: "Grilled Salmon", qty: 1, price: 28.99, mods: "Medium rare" },
      { name: "House Wine", qty: 2, price: 8.0, mods: "" },
    ],
    total: 57.98,
    subtotal: 49.98,
    tax: 5.0,
    service: 3.0,
    tip: 0,
    status: "In Progress" as const,
    orderType: "Dine-in",
    time: "10 min ago",
    timestamp: "2025-01-10T18:45:00",
    staff: "John Smith",
    staffId: "S1",
    paymentStatus: "Pending",
    paymentMethod: "",
    transactionId: "",
    specialNotes: "Customer has nut allergy",
    urgency: "warning" as const,
    timeline: [
      { event: "Order placed", time: "18:45", user: "John Smith", avatar: "JS" },
      { event: "Sent to kitchen", time: "18:46", user: "John Smith", avatar: "JS" },
      { event: "Preparing", time: "18:48", user: "Kitchen", avatar: "K" },
    ],
  },
  {
    id: "ORD-1235",
    table: "2",
    customer: "Michael Chen",
    items: [
      { name: "Margherita Pizza", qty: 1, price: 18.99, mods: "Extra cheese" },
      { name: "Tiramisu", qty: 1, price: 8.99, mods: "" },
    ],
    total: 32.18,
    subtotal: 27.98,
    tax: 2.8,
    service: 1.4,
    tip: 0,
    status: "Pending" as const,
    orderType: "Dine-in",
    time: "5 min ago",
    timestamp: "2025-01-10T18:50:00",
    staff: "Maria Garcia",
    staffId: "S2",
    paymentStatus: "Pending",
    paymentMethod: "",
    transactionId: "",
    specialNotes: "",
    urgency: "delayed" as const,
    timeline: [{ event: "Order placed", time: "18:50", user: "Maria Garcia", avatar: "MG" }],
  },
  {
    id: "ORD-1236",
    table: "8",
    customer: "Emily Davis",
    items: [
      { name: "Ribeye Steak", qty: 2, price: 42.99, mods: "Well done" },
      { name: "Caesar Salad", qty: 2, price: 12.99, mods: "" },
      { name: "Red Wine", qty: 1, price: 12.0, mods: "" },
    ],
    total: 136.95,
    subtotal: 123.96,
    tax: 9.9,
    service: 3.09,
    tip: 0,
    status: "Ready" as const,
    orderType: "Dine-in",
    time: "2 min ago",
    timestamp: "2025-01-10T18:53:00",
    staff: "John Smith",
    staffId: "S1",
    paymentStatus: "Pending",
    paymentMethod: "",
    transactionId: "",
    specialNotes: "Celebrating anniversary",
    urgency: "on-time" as const,
    timeline: [
      { event: "Order placed", time: "18:30", user: "John Smith", avatar: "JS" },
      { event: "Sent to kitchen", time: "18:31", user: "John Smith", avatar: "JS" },
      { event: "Preparing", time: "18:35", user: "Kitchen", avatar: "K" },
      { event: "Ready for pickup", time: "18:53", user: "Kitchen", avatar: "K" },
    ],
  },
  {
    id: "ORD-1237",
    table: "12",
    customer: "James Wilson",
    items: [
      { name: "Grilled Salmon", qty: 1, price: 28.99, mods: "" },
      { name: "House Salad", qty: 1, price: 9.99, mods: "Dressing on side" },
      { name: "Iced Tea", qty: 2, price: 3.5, mods: "" },
    ],
    total: 49.48,
    subtotal: 45.98,
    tax: 3.5,
    service: 0,
    tip: 0,
    status: "In Progress" as const,
    orderType: "Dine-in",
    time: "15 min ago",
    timestamp: "2025-01-10T18:40:00",
    staff: "David Lee",
    staffId: "S3",
    paymentStatus: "Pending",
    paymentMethod: "",
    transactionId: "",
    specialNotes: "",
    urgency: "on-time" as const,
    timeline: [
      { event: "Order placed", time: "18:40", user: "David Lee", avatar: "DL" },
      { event: "Sent to kitchen", time: "18:41", user: "David Lee", avatar: "DL" },
      { event: "Preparing", time: "18:43", user: "Kitchen", avatar: "K" },
    ],
  },
  {
    id: "ORD-1238",
    table: "3",
    customer: "Lisa Anderson",
    items: [
      { name: "Caesar Salad", qty: 1, price: 12.99, mods: "" },
      { name: "Lemonade", qty: 1, price: 3.5, mods: "" },
    ],
    total: 18.99,
    subtotal: 16.49,
    tax: 1.5,
    service: 1.0,
    tip: 3.5,
    status: "Completed" as const,
    orderType: "Dine-in",
    time: "30 min ago",
    timestamp: "2025-01-10T18:25:00",
    staff: "John Smith",
    staffId: "S1",
    paymentStatus: "Paid",
    paymentMethod: "Credit Card",
    transactionId: "TXN-9876543",
    specialNotes: "",
    urgency: "on-time" as const,
    timeline: [
      { event: "Order placed", time: "18:25", user: "John Smith", avatar: "JS" },
      { event: "Sent to kitchen", time: "18:26", user: "John Smith", avatar: "JS" },
      { event: "Preparing", time: "18:28", user: "Kitchen", avatar: "K" },
      { event: "Served", time: "18:35", user: "John Smith", avatar: "JS" },
      { event: "Payment received", time: "18:55", user: "John Smith", avatar: "JS" },
    ],
  },
  {
    id: "ORD-1239",
    table: "7",
    customer: "Robert Taylor",
    items: [
      { name: "Margherita Pizza", qty: 1, price: 18.99, mods: "" },
      { name: "Beer", qty: 2, price: 6.0, mods: "" },
    ],
    total: 34.99,
    subtotal: 30.99,
    tax: 2.5,
    service: 1.5,
    tip: 0,
    status: "In Progress" as const,
    orderType: "Dine-in",
    time: "8 min ago",
    timestamp: "2025-01-10T18:47:00",
    staff: "Maria Garcia",
    staffId: "S2",
    paymentStatus: "Pending",
    paymentMethod: "",
    transactionId: "",
    specialNotes: "",
    urgency: "on-time" as const,
    timeline: [
      { event: "Order placed", time: "18:47", user: "Maria Garcia", avatar: "MG" },
      { event: "Sent to kitchen", time: "18:48", user: "Maria Garcia", avatar: "MG" },
    ],
  },
  {
    id: "ORD-1240",
    table: "15",
    customer: "Amanda White",
    items: [
      { name: "Grilled Salmon", qty: 1, price: 28.99, mods: "" },
      { name: "House Wine", qty: 1, price: 8.0, mods: "" },
    ],
    total: 42.49,
    subtotal: 36.99,
    tax: 3.0,
    service: 2.5,
    tip: 0,
    status: "Pending" as const,
    orderType: "Dine-in",
    time: "3 min ago",
    timestamp: "2025-01-10T18:52:00",
    staff: "John Smith",
    staffId: "S1",
    paymentStatus: "Pending",
    paymentMethod: "",
    transactionId: "",
    specialNotes: "Window seat requested",
    urgency: "on-time" as const,
    timeline: [{ event: "Order placed", time: "18:52", user: "John Smith", avatar: "JS" }],
  },
  {
    id: "ORD-1241",
    table: "9",
    customer: "David Brown",
    items: [
      { name: "Ribeye Steak", qty: 1, price: 42.99, mods: "Medium" },
      { name: "Caesar Salad", qty: 1, price: 12.99, mods: "" },
    ],
    total: 64.48,
    subtotal: 55.98,
    tax: 5.5,
    service: 3.0,
    tip: 0,
    status: "Cancelled" as const,
    orderType: "Dine-in",
    time: "1 hour ago",
    timestamp: "2025-01-10T17:55:00",
    staff: "David Lee",
    staffId: "S3",
    paymentStatus: "Refunded",
    paymentMethod: "Credit Card",
    transactionId: "TXN-9876542",
    specialNotes: "Customer left before order arrived",
    urgency: "on-time" as const,
    timeline: [
      { event: "Order placed", time: "17:55", user: "David Lee", avatar: "DL" },
      { event: "Sent to kitchen", time: "17:56", user: "David Lee", avatar: "DL" },
      { event: "Cancelled", time: "18:10", user: "Manager", avatar: "M" },
      { event: "Refunded", time: "18:12", user: "Manager", avatar: "M" },
    ],
  },
  {
    id: "ORD-1242",
    table: "4",
    customer: "Jennifer Martinez",
    items: [
      { name: "Margherita Pizza", qty: 2, price: 18.99, mods: "" },
      { name: "Tiramisu", qty: 2, price: 8.99, mods: "" },
      { name: "Soda", qty: 4, price: 3.0, mods: "" },
    ],
    total: 71.96,
    subtotal: 67.96,
    tax: 4.0,
    service: 0,
    tip: 12.0,
    status: "Completed" as const,
    orderType: "Dine-in",
    time: "45 min ago",
    timestamp: "2025-01-10T18:10:00",
    staff: "Maria Garcia",
    staffId: "S2",
    paymentStatus: "Paid",
    paymentMethod: "Cash",
    transactionId: "TXN-9876544",
    specialNotes: "",
    urgency: "on-time" as const,
    timeline: [
      { event: "Order placed", time: "18:10", user: "Maria Garcia", avatar: "MG" },
      { event: "Sent to kitchen", time: "18:11", user: "Maria Garcia", avatar: "MG" },
      { event: "Preparing", time: "18:13", user: "Kitchen", avatar: "K" },
      { event: "Served", time: "18:28", user: "Maria Garcia", avatar: "MG" },
      { event: "Payment received", time: "18:55", user: "Maria Garcia", avatar: "MG" },
    ],
  },
  {
    id: "ORD-1243",
    table: "11",
    customer: "Christopher Lee",
    items: [{ name: "Grilled Salmon", qty: 1, price: 28.99, mods: "" }],
    total: 33.49,
    subtotal: 28.99,
    tax: 2.5,
    service: 2.0,
    tip: 0,
    status: "Ready" as const,
    orderType: "Dine-in",
    time: "1 min ago",
    timestamp: "2025-01-10T18:54:00",
    staff: "David Lee",
    staffId: "S3",
    paymentStatus: "Pending",
    paymentMethod: "",
    transactionId: "",
    specialNotes: "",
    urgency: "on-time" as const,
    timeline: [
      { event: "Order placed", time: "18:35", user: "David Lee", avatar: "DL" },
      { event: "Sent to kitchen", time: "18:36", user: "David Lee", avatar: "DL" },
      { event: "Preparing", time: "18:38", user: "Kitchen", avatar: "K" },
      { event: "Ready for pickup", time: "18:54", user: "Kitchen", avatar: "K" },
    ],
  },
]

export const mockStaffWorkload = [
  { id: "S1", name: "John Smith", role: "Server", activeOrders: 4, load: "high" as const },
  { id: "S2", name: "Maria Garcia", role: "Server", activeOrders: 3, load: "medium" as const },
  { id: "S3", name: "David Lee", role: "Server", activeOrders: 2, load: "low" as const },
  { id: "S4", name: "Sarah Wilson", role: "Server", activeOrders: 5, load: "high" as const },
  { id: "S5", name: "Tom Anderson", role: "Bartender", activeOrders: 3, load: "medium" as const },
  { id: "S6", name: "Lisa Chen", role: "Server", activeOrders: 1, load: "low" as const },
  { id: "S7", name: "Mike Johnson", role: "Server", activeOrders: 4, load: "high" as const },
  { id: "S8", name: "Emma Davis", role: "Host", activeOrders: 0, load: "low" as const },
  { id: "S9", name: "Alex Martinez", role: "Server", activeOrders: 3, load: "medium" as const },
  { id: "S10", name: "Rachel Brown", role: "Server", activeOrders: 2, load: "low" as const },
]

export const mockRecentOrderActivity = [
  { id: "A1", message: "Order #1243 marked as ready", time: "1 min ago" },
  { id: "A2", message: "Order #1236 marked as ready", time: "2 min ago" },
  { id: "A3", message: "New order #1240 placed", time: "3 min ago" },
  { id: "A4", message: "Order #1239 sent to kitchen", time: "8 min ago" },
  { id: "A5", message: "Order #1234 preparing", time: "10 min ago" },
]

export const mockOrdersPerformance = [
  { time: "12 PM", orders: 8 },
  { time: "1 PM", orders: 12 },
  { time: "2 PM", orders: 6 },
  { time: "3 PM", orders: 4 },
  { time: "4 PM", orders: 3 },
  { time: "5 PM", orders: 7 },
  { time: "6 PM", orders: 10 },
]
