export interface PromotionTemplate {
  id: string
  name: string
  icon: string
  emoji: string
  description: string
  category: string
  popularity: string
  color: string
  presets: {
    name: string
    description: string
    type: "percentage" | "fixed" | "bogo" | "happy_hour"
    discountValue: number
    discountUnit: string
    targetType: string
    targetCategory?: string
    targetItems?: string[]
    minOrderAmount?: number
    startTime: string
    endTime: string
    recurring: boolean
    recurringType?: string
    activeDays: string[]
    maxRedemptions?: number
    perCustomerLimit?: number
    perCustomerPeriod?: string
    eligibility?: string
    requiresVerification?: boolean
  }
  estimatedROI: string
  avgRedemptionRate: string
  usageCount: number
}

export const promotionTemplates: PromotionTemplate[] = [
  {
    id: "template_001",
    name: "Happy Hour",
    icon: "Beer",
    emoji: "🍺",
    description: "Time-based discount on beverages",
    category: "Beverage",
    popularity: "Most Popular",
    color: "hsl(var(--chart-1))",
    presets: {
      name: "Happy Hour 20% Off Drinks",
      description: "Daily happy hour discount to drive early evening traffic",
      type: "percentage",
      discountValue: 20,
      discountUnit: "%",
      targetType: "category",
      targetCategory: "Beverages",
      startTime: "17:00",
      endTime: "19:00",
      recurring: true,
      recurringType: "daily",
      activeDays: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
      maxRedemptions: 500,
      perCustomerLimit: 1,
      perCustomerPeriod: "day",
    },
    estimatedROI: "3.2x",
    avgRedemptionRate: "45%",
    usageCount: 234,
  },
  {
    id: "template_002",
    name: "BOGO Deal",
    icon: "Gift",
    emoji: "🎁",
    description: "Buy one get one free promotion",
    category: "Food",
    popularity: "Trending",
    color: "hsl(var(--chart-3))",
    presets: {
      name: "BOGO Tuesday Special",
      description: "Buy one get one free to boost weekday sales",
      type: "bogo",
      discountValue: 100,
      discountUnit: "%",
      targetType: "category",
      targetCategory: "Pizza",
      startTime: "00:00",
      endTime: "23:59",
      recurring: true,
      recurringType: "weekly",
      activeDays: ["tuesday"],
      maxRedemptions: 1000,
      perCustomerLimit: 1,
      perCustomerPeriod: "day",
    },
    estimatedROI: "2.8x",
    avgRedemptionRate: "52%",
    usageCount: 189,
  },
  {
    id: "template_003",
    name: "First-Time Customer",
    icon: "UserPlus",
    emoji: "👤",
    description: "Welcome discount for new customers",
    category: "Acquisition",
    popularity: "High Converting",
    color: "hsl(var(--chart-2))",
    presets: {
      name: "First-Time Customer €10 Off",
      description: "Welcome discount for new customer acquisition",
      type: "fixed",
      discountValue: 10,
      discountUnit: "€",
      targetType: "entire_order",
      minOrderAmount: 25,
      startTime: "00:00",
      endTime: "23:59",
      recurring: false,
      activeDays: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
      maxRedemptions: 1000,
      perCustomerLimit: 1,
      perCustomerPeriod: "lifetime",
      eligibility: "new_customers_only",
    },
    estimatedROI: "4.1x",
    avgRedemptionRate: "38%",
    usageCount: 456,
  },
  {
    id: "template_004",
    name: "Loyalty Reward",
    icon: "Award",
    emoji: "⭐",
    description: "Reward for repeat customers",
    category: "Retention",
    popularity: "Staff Favorite",
    color: "hsl(var(--chart-4))",
    presets: {
      name: "VIP Loyalty 15% Off",
      description: "Exclusive discount for loyal customers",
      type: "percentage",
      discountValue: 15,
      discountUnit: "%",
      targetType: "entire_order",
      minOrderAmount: 30,
      startTime: "00:00",
      endTime: "23:59",
      recurring: false,
      activeDays: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
      maxRedemptions: 500,
      perCustomerLimit: 2,
      perCustomerPeriod: "month",
      eligibility: "vip_loyalty_members",
    },
    estimatedROI: "3.5x",
    avgRedemptionRate: "61%",
    usageCount: 312,
  },
  {
    id: "template_005",
    name: "Lunch Special",
    icon: "UtensilsCrossed",
    emoji: "🍽️",
    description: "Midday discount to drive lunch traffic",
    category: "Food",
    popularity: "Popular",
    color: "hsl(var(--chart-3))",
    presets: {
      name: "Lunch Special €5 Off €25+",
      description: "Weekday lunch discount to boost midday sales",
      type: "fixed",
      discountValue: 5,
      discountUnit: "€",
      targetType: "entire_order",
      minOrderAmount: 25,
      startTime: "11:00",
      endTime: "14:00",
      recurring: true,
      recurringType: "weekly",
      activeDays: ["monday", "tuesday", "wednesday", "thursday", "friday"],
      maxRedemptions: 200,
      perCustomerLimit: 1,
      perCustomerPeriod: "day",
    },
    estimatedROI: "2.6x",
    avgRedemptionRate: "42%",
    usageCount: 167,
  },
  {
    id: "template_006",
    name: "Weekend Brunch",
    icon: "Coffee",
    emoji: "☕",
    description: "Weekend morning promotion",
    category: "Food",
    popularity: "Seasonal",
    color: "hsl(var(--chart-2))",
    presets: {
      name: "Weekend Brunch 15% Off",
      description: "Weekend brunch discount to boost morning sales",
      type: "percentage",
      discountValue: 15,
      discountUnit: "%",
      targetType: "category",
      targetCategory: "Brunch Items",
      startTime: "09:00",
      endTime: "14:00",
      recurring: true,
      recurringType: "weekly",
      activeDays: ["saturday", "sunday"],
      maxRedemptions: 1200,
      perCustomerLimit: 2,
      perCustomerPeriod: "day",
    },
    estimatedROI: "3.1x",
    avgRedemptionRate: "48%",
    usageCount: 201,
  },
  {
    id: "template_007",
    name: "Student Discount",
    icon: "GraduationCap",
    emoji: "🎓",
    description: "Ongoing student discount program",
    category: "Demographic",
    popularity: "Long-term",
    color: "hsl(var(--chart-1))",
    presets: {
      name: "Student Discount 10%",
      description: "Student ID discount for university students",
      type: "percentage",
      discountValue: 10,
      discountUnit: "%",
      targetType: "entire_order",
      minOrderAmount: 0,
      startTime: "00:00",
      endTime: "23:59",
      recurring: false,
      activeDays: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
      maxRedemptions: 10000,
      perCustomerLimit: 1,
      perCustomerPeriod: "day",
      eligibility: "custom_segment",
      requiresVerification: true,
    },
    estimatedROI: "2.9x",
    avgRedemptionRate: "24%",
    usageCount: 523,
  },
  {
    id: "template_008",
    name: "Late Night Deal",
    icon: "Moon",
    emoji: "🌙",
    description: "Late night discount for delivery",
    category: "Delivery",
    popularity: "New",
    color: "hsl(var(--chart-4))",
    presets: {
      name: "Late Night €3 Off Delivery",
      description: "Late night delivery discount",
      type: "fixed",
      discountValue: 3,
      discountUnit: "€",
      targetType: "delivery_orders",
      minOrderAmount: 15,
      startTime: "22:00",
      endTime: "02:00",
      recurring: true,
      recurringType: "daily",
      activeDays: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
      maxRedemptions: 500,
      perCustomerLimit: 1,
      perCustomerPeriod: "day",
    },
    estimatedROI: "2.4x",
    avgRedemptionRate: "31%",
    usageCount: 89,
  },
]
