import type { Invoice, InvoiceKPIs } from "./types"

export const generateInvoices = (): Invoice[] => {
  const invoices: Invoice[] = []
  const currentDate = new Date()

  // Generate subscription invoices for the past 12 months
  for (let i = 0; i < 12; i++) {
    const invoiceDate = new Date(currentDate)
    invoiceDate.setMonth(invoiceDate.getMonth() - i)
    invoiceDate.setDate(15)
    invoiceDate.setHours(10, 15 + i, 0, 0)

    const dueDate = new Date(invoiceDate)
    const paidDate =
      i === 0 ? new Date(invoiceDate.getTime() + 8 * 60000) : new Date(invoiceDate.getTime() + 30 * 60000)

    const invoiceNumber = `2024-${String(11 - i).padStart(4, "0")}`
    const amount = i < 4 ? 150 : 125
    const tax = amount * 0.18
    const total = amount + tax

    invoices.push({
      id: `inv_${invoiceDate.getTime()}`,
      invoiceNumber,
      invoiceId: `inv_${invoiceDate.getFullYear()}${String(invoiceDate.getMonth() + 1).padStart(2, "0")}${String(invoiceDate.getDate()).padStart(2, "0")}`,
      date: invoiceDate,
      dueDate,
      paidDate: i !== 5 ? paidDate : undefined,
      type: "subscription",
      typeDescription: "Monthly - Pro",
      status: i === 5 ? "past_due" : "paid",
      amount,
      currency: "EUR",
      paymentMethod: "Visa ••42",
      paymentMethodType: i === 5 ? "failed" : "auto_charge",
      cardLast4: "4242",
      reviewed: i < 6,
      reviewedBy: i < 6 ? "Sarah Johnson (Owner)" : undefined,
      reviewedAt: i < 6 ? new Date(invoiceDate.getTime() + 5 * 60 * 60 * 1000) : undefined,
      reviewNote: i < 6 ? "Reviewed for accounting reconciliation." : undefined,
      billTo: {
        businessName: "BerryTap Restaurant",
        location: "Valletta Main Location",
        address: "123 Republic Street",
        city: "Valletta",
        postalCode: "VLT 1234",
        country: "Malta",
        vatId: "MT12345678",
        contact: "Sarah Johnson",
        email: "billing@berrytap.com",
      },
      lineItems: [
        {
          description: "BerryTap Pro - Monthly Plan",
          details: `Period: ${invoiceDate.toLocaleDateString("en-US", { month: "short", day: "numeric" })} - ${new Date(invoiceDate.getTime() + 30 * 24 * 60 * 60 * 1000).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}${i < 4 ? "\n3 locations, unlimited transactions" : ""}`,
          quantity: 1,
          unitPrice: amount - (i < 4 ? 25 : 0),
          total: amount - (i < 4 ? 25 : 0),
        },
        ...(i < 4
          ? [
              {
                description: "Additional Team Member",
                details: "User: michael.chen@berrytap.com",
                quantity: 1,
                unitPrice: 25,
                total: 25,
              },
            ]
          : []),
      ],
      subtotal: amount,
      tax,
      taxRate: 18,
      credits: 0,
      total,
      amountPaid: i !== 5 ? total : 0,
      balance: i === 5 ? total : 0,
      periodStart: invoiceDate,
      periodEnd: new Date(invoiceDate.getTime() + 30 * 24 * 60 * 60 * 1000),
      transactionId: i !== 5 ? `tx_${invoiceDate.getTime()}` : undefined,
      paymentFailureReason: i === 5 ? "Card declined (insufficient funds)" : undefined,
      lastAttemptDate: i === 5 ? invoiceDate : undefined,
      notes: "Generated by Stripe Billing\nQuestions about this invoice?\nContact: support@berrytap.com",
      lateFee: i === 5 ? 25 : undefined,
      daysOverdue:
        i === 5 ? Math.floor((currentDate.getTime() - dueDate.getTime()) / (24 * 60 * 60 * 1000)) : undefined,
    })
  }

  // Add a one-off invoice
  const oneOffDate = new Date(currentDate)
  oneOffDate.setMonth(oneOffDate.getMonth() - 3)
  oneOffDate.setDate(20)
  oneOffDate.setHours(14, 45, 0, 0)

  invoices.push({
    id: `inv_${oneOffDate.getTime()}`,
    invoiceNumber: "2024-0008",
    invoiceId: `inv_${oneOffDate.getFullYear()}${String(oneOffDate.getMonth() + 1).padStart(2, "0")}20`,
    date: oneOffDate,
    dueDate: oneOffDate,
    paidDate: new Date(oneOffDate.getTime() + 15 * 60000),
    type: "one_off",
    typeDescription: "Additional user",
    status: "paid",
    amount: 50,
    currency: "EUR",
    paymentMethod: "Visa ••42",
    paymentMethodType: "manual",
    cardLast4: "4242",
    reviewed: true,
    reviewedBy: "Sarah Johnson (Owner)",
    reviewedAt: new Date(oneOffDate.getTime() + 2 * 60 * 60 * 1000),
    billTo: {
      businessName: "BerryTap Restaurant",
      location: "Valletta Main Location",
      address: "123 Republic Street",
      city: "Valletta",
      postalCode: "VLT 1234",
      country: "Malta",
      vatId: "MT12345678",
      contact: "Sarah Johnson",
      email: "billing@berrytap.com",
    },
    lineItems: [
      {
        description: "Additional Team Member",
        details: "One-time charge: Additional team member",
        quantity: 1,
        unitPrice: 50,
        total: 50,
      },
    ],
    subtotal: 50,
    tax: 9,
    taxRate: 18,
    credits: 0,
    total: 59,
    amountPaid: 59,
    balance: 0,
    transactionId: `tx_${oneOffDate.getTime()}`,
    notes: "One-time charge for additional team member",
  })

  // Add a credit note
  const creditDate = new Date(currentDate)
  creditDate.setMonth(creditDate.getMonth() - 4)
  creditDate.setDate(1)
  creditDate.setHours(9, 30, 0, 0)

  invoices.push({
    id: `inv_${creditDate.getTime()}`,
    invoiceNumber: "2024-0006-CR",
    invoiceId: `inv_${creditDate.getFullYear()}${String(creditDate.getMonth() + 1).padStart(2, "0")}01cr`,
    date: creditDate,
    dueDate: creditDate,
    paidDate: creditDate,
    type: "credit",
    typeDescription: "Promo credit",
    status: "paid",
    amount: -25,
    currency: "EUR",
    paymentMethod: "N/A",
    paymentMethodType: "n/a",
    reviewed: true,
    reviewedBy: "Sarah Johnson (Owner)",
    reviewedAt: new Date(creditDate.getTime() + 1 * 60 * 60 * 1000),
    billTo: {
      businessName: "BerryTap Restaurant",
      location: "Valletta Main Location",
      address: "123 Republic Street",
      city: "Valletta",
      postalCode: "VLT 1234",
      country: "Malta",
      vatId: "MT12345678",
      contact: "Sarah Johnson",
      email: "billing@berrytap.com",
    },
    lineItems: [
      {
        description: "Promotional credit - Summer promotion",
        details: "Applied to invoice 2024-0007",
        quantity: 1,
        unitPrice: -25,
        total: -25,
      },
    ],
    subtotal: -25,
    tax: 0,
    taxRate: 0,
    credits: -25,
    total: -25,
    amountPaid: 0,
    balance: 0,
    notes: "Promotional credit - Summer promotion\nApplied to invoice 2024-0007",
  })

  return invoices.sort((a, b) => b.date.getTime() - a.date.getTime())
}

export const calculateKPIs = (invoices: Invoice[]): InvoiceKPIs => {
  const unpaidInvoices = invoices.filter((inv) => inv.status === "unpaid" || inv.status === "past_due")
  const pastDueInvoices = invoices.filter((inv) => inv.status === "past_due")

  const currentMonth = new Date().getMonth()
  const currentYear = new Date().getFullYear()
  const thisMonthInvoices = invoices.filter(
    (inv) => inv.date.getMonth() === currentMonth && inv.date.getFullYear() === currentYear,
  )

  const lastInvoice = invoices.length > 0 ? invoices[0] : null

  const nextDue = invoices.find((inv) => inv.status === "unpaid" && inv.dueDate > new Date())

  return {
    totalDue: unpaidInvoices.reduce((sum, inv) => sum + inv.balance, 0),
    pastDueCount: pastDueInvoices.length,
    pastDueAmount: pastDueInvoices.reduce((sum, inv) => sum + inv.balance, 0),
    lastInvoice: lastInvoice
      ? {
          date: lastInvoice.date,
          number: lastInvoice.invoiceNumber,
          amount: lastInvoice.amount,
          status: lastInvoice.status,
        }
      : null,
    thisMonth: {
      amount: thisMonthInvoices.reduce((sum, inv) => sum + inv.amount, 0),
      count: thisMonthInvoices.length,
      paid: thisMonthInvoices.every((inv) => inv.status === "paid"),
    },
    nextDueDate: nextDue?.dueDate,
  }
}

export const mockInvoices = generateInvoices()
export const mockKPIs = calculateKPIs(mockInvoices)
