import type { Integration, Webhook, WebhookDelivery } from "./types"

export const mockIntegrations: Integration[] = [
  // Payment integrations
  {
    id: "int_stripe_001",
    key: "stripe",
    name: "Stripe",
    category: "payment",
    description: "Accept card payments and subscriptions",
    status: "connected",
    provider: "Stripe Inc.",
    logo: "💳",
    config: {
      accountId: "acc_1A2B3C4D",
      mode: "live",
    },
    features: [
      { name: "Payment processing", enabled: true },
      { name: "Subscription billing", enabled: true },
      { name: "Customer portal", enabled: true },
      { name: "Automatic payouts", enabled: true },
    ],
    stats: {
      todayCount: 142,
      todayValue: 4234.5,
      successRate: 99.3,
    },
    lastSyncAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    lastSyncStatus: "success",
    webhookUrl: "https://app.berrytap.com/webhooks/stripe",
    webhookEvents: ["payment_intent.succeeded", "payment_intent.failed", "charge.refunded"],
    connectedAt: "2024-10-01T10:00:00Z",
    connectedBy: "user_001",
    connectedByName: "Sarah Johnson",
    documentation: "https://stripe.com/docs",
    supportUrl: "https://support.stripe.com",
    createdAt: "2024-10-01T10:00:00Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "int_paypal_001",
    key: "paypal",
    name: "PayPal",
    category: "payment",
    description: "Digital wallet payments",
    status: "setup_needed",
    provider: "PayPal",
    logo: "💰",
    features: [
      { name: "PayPal checkout", enabled: false },
      { name: "PayPal Credit", enabled: false },
    ],
    documentation: "https://developer.paypal.com/docs",
    createdAt: "2024-10-15T10:00:00Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "int_square_001",
    key: "square",
    name: "Square",
    category: "payment",
    description: "Point of sale integration",
    status: "not_connected",
    provider: "Square Inc.",
    logo: "🏦",
    features: [
      { name: "In-person payments", enabled: false },
      { name: "Inventory sync", enabled: false },
      { name: "Staff management", enabled: false },
    ],
    documentation: "https://developer.squareup.com/docs",
    createdAt: "2024-10-01T10:00:00Z",
    updatedAt: new Date().toISOString(),
  },

  // Delivery integrations
  {
    id: "int_ubereats_001",
    key: "uber_eats",
    name: "Uber Eats",
    category: "delivery",
    description: "Online ordering platform",
    status: "connected",
    provider: "Uber Technologies",
    logo: "🍔",
    config: {
      storeId: "store_uber_123",
      mode: "live",
    },
    features: [
      { name: "Menu sync", enabled: true },
      { name: "Order management", enabled: true },
      { name: "Auto-accept orders", enabled: true },
    ],
    stats: {
      todayCount: 12,
      successRate: 100,
    },
    lastSyncAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    lastSyncStatus: "success",
    connectedAt: "2024-09-15T10:00:00Z",
    connectedBy: "user_001",
    connectedByName: "Sarah Johnson",
    documentation: "https://developer.uber.com/docs/eats",
    createdAt: "2024-09-15T10:00:00Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "int_deliveroo_001",
    key: "deliveroo",
    name: "Deliveroo",
    category: "delivery",
    description: "Food delivery marketplace",
    status: "not_connected",
    provider: "Deliveroo",
    logo: "🚴",
    features: [
      { name: "Menu sync", enabled: false },
      { name: "Order management", enabled: false },
    ],
    documentation: "https://deliveroo.co.uk/developers",
    createdAt: "2024-10-01T10:00:00Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "int_custom_delivery_001",
    key: "custom_delivery",
    name: "Custom Delivery",
    category: "delivery",
    description: "Your own delivery fleet integration",
    status: "not_connected",
    provider: "Custom",
    logo: "📦",
    features: [{ name: "API integration", enabled: false }],
    documentation: "https://docs.berrytap.com/custom-delivery",
    createdAt: "2024-10-01T10:00:00Z",
    updatedAt: new Date().toISOString(),
  },

  // Messaging integrations
  {
    id: "int_twilio_001",
    key: "twilio",
    name: "Twilio (SMS)",
    category: "messaging",
    description: "Send SMS notifications to customers",
    status: "connected",
    provider: "Twilio Inc.",
    logo: "📱",
    config: {
      accountSid: "AC********************************",
      phoneNumber: "+1 555 123 4567",
    },
    features: [
      { name: "SMS notifications", enabled: true },
      { name: "Order updates", enabled: true },
    ],
    stats: {
      todayCount: 89,
      successRate: 98.5,
    },
    lastSyncAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    lastSyncStatus: "success",
    connectedAt: "2024-09-01T10:00:00Z",
    connectedBy: "user_001",
    connectedByName: "Sarah Johnson",
    documentation: "https://www.twilio.com/docs",
    createdAt: "2024-09-01T10:00:00Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "int_whatsapp_001",
    key: "whatsapp",
    name: "WhatsApp Business",
    category: "messaging",
    description: "WhatsApp messaging for customers",
    status: "connected",
    provider: "Meta Platforms",
    logo: "💬",
    config: {
      businessAccountId: "whatsapp_biz_123",
    },
    features: [
      { name: "WhatsApp messages", enabled: true },
      { name: "Order confirmations", enabled: true },
    ],
    stats: {
      todayCount: 45,
      successRate: 99.1,
    },
    lastSyncAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    lastSyncStatus: "success",
    connectedAt: "2024-09-20T10:00:00Z",
    connectedBy: "user_002",
    connectedByName: "John Smith",
    documentation: "https://developers.facebook.com/docs/whatsapp",
    createdAt: "2024-09-20T10:00:00Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "int_sendgrid_001",
    key: "sendgrid",
    name: "SendGrid",
    category: "messaging",
    description: "Transactional email service",
    status: "not_connected",
    provider: "Twilio SendGrid",
    logo: "📧",
    features: [
      { name: "Email notifications", enabled: false },
      { name: "Marketing emails", enabled: false },
    ],
    documentation: "https://sendgrid.com/docs",
    createdAt: "2024-10-01T10:00:00Z",
    updatedAt: new Date().toISOString(),
  },

  // Accounting integrations
  {
    id: "int_quickbooks_001",
    key: "quickbooks",
    name: "QuickBooks",
    category: "accounting",
    description: "Sync sales and expenses",
    status: "not_connected",
    provider: "Intuit",
    logo: "📗",
    features: [
      { name: "Sales sync", enabled: false },
      { name: "Expense tracking", enabled: false },
      { name: "Automatic reconciliation", enabled: false },
    ],
    documentation: "https://developer.intuit.com/docs",
    createdAt: "2024-10-01T10:00:00Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "int_xero_001",
    key: "xero",
    name: "Xero",
    category: "accounting",
    description: "Cloud accounting platform",
    status: "not_connected",
    provider: "Xero Limited",
    logo: "📘",
    features: [
      { name: "Sales sync", enabled: false },
      { name: "Invoice management", enabled: false },
    ],
    documentation: "https://developer.xero.com/documentation",
    createdAt: "2024-10-01T10:00:00Z",
    updatedAt: new Date().toISOString(),
  },
]

export const mockWebhooks: Webhook[] = [
  {
    id: "webhook_001",
    name: "Orders Webhook",
    description: "Receive order events",
    url: "https://api.example.com/webhooks/orders",
    events: ["order.created", "order.completed"],
    secret: "whsec_abc123...",
    retryConfig: {
      enabled: true,
      maxAttempts: 3,
      strategy: "exponential",
    },
    timeout: 30,
    enabled: true,
    stats: {
      totalDeliveries: 1234,
      successfulDeliveries: 1220,
      failedDeliveries: 14,
      successRate: 98.9,
    },
    lastDeliveryAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    lastDeliveryStatus: "success",
    createdBy: "user_001",
    createdByName: "Sarah Johnson",
    createdAt: "2024-09-01T10:00:00Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "webhook_002",
    name: "Analytics Webhook",
    description: "All events for analytics",
    url: "https://analytics.example.com/events",
    events: ["*"],
    retryConfig: {
      enabled: true,
      maxAttempts: 5,
      strategy: "linear",
    },
    timeout: 15,
    enabled: true,
    stats: {
      totalDeliveries: 5678,
      successfulDeliveries: 5650,
      failedDeliveries: 28,
      successRate: 99.5,
    },
    lastDeliveryAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    lastDeliveryStatus: "success",
    createdBy: "user_001",
    createdByName: "Sarah Johnson",
    createdAt: "2024-09-15T10:00:00Z",
    updatedAt: new Date().toISOString(),
  },
]

export const mockWebhookDeliveries: WebhookDelivery[] = [
  {
    id: "delivery_001",
    webhookId: "webhook_001",
    event: "order.completed",
    request: {
      method: "POST",
      url: "https://api.example.com/webhooks/orders",
      headers: {
        "Content-Type": "application/json",
        "X-BerryTap-Signature": "sha256=abc123...",
      },
      body: {
        event: "order.completed",
        data: { order_id: "ord_20241121_12345" },
      },
    },
    response: {
      status: 200,
      statusText: "OK",
      time: 123,
    },
    attempts: 1,
    maxAttempts: 3,
    status: "success",
    metadata: { orderId: "ord_20241121_12345" },
    createdAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
  },
  {
    id: "delivery_002",
    webhookId: "webhook_001",
    event: "order.created",
    request: {
      method: "POST",
      url: "https://api.example.com/webhooks/orders",
      headers: {
        "Content-Type": "application/json",
        "X-BerryTap-Signature": "sha256=def456...",
      },
      body: {
        event: "order.created",
        data: { order_id: "ord_20241121_12344" },
      },
    },
    attempts: 3,
    maxAttempts: 3,
    status: "failed",
    error: {
      code: "TIMEOUT",
      message: "Request timeout after 30 seconds",
    },
    retryHistory: [
      {
        attempt: 1,
        timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        status: "failed",
        error: "Timeout",
      },
      {
        attempt: 2,
        timestamp: new Date(Date.now() - 29 * 60 * 1000).toISOString(),
        status: "failed",
        error: "Timeout",
      },
      {
        attempt: 3,
        timestamp: new Date(Date.now() - 27 * 60 * 1000).toISOString(),
        status: "failed",
        error: "Timeout",
      },
    ],
    metadata: { orderId: "ord_20241121_12344" },
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
]
