import type { NotificationChannel, NotificationTemplate, NotificationTrigger, DeliveryLog } from "./types"

export const mockChannels: NotificationChannel[] = [
  {
    id: "email",
    name: "Email",
    icon: "📧",
    type: "email",
    connected: true,
    active: true,
    provider: "SendGrid",
    status: "healthy",
    sentToday: 142,
    failedToday: 2,
    deliveryRate: 98.6,
    lastTested: {
      date: "2 hours ago",
      by: "Sarah J.",
      result: "success",
    },
    config: {
      apiKey: "sk_live_••••••••••••3xY2",
      senderName: "BerryTap Restaurant",
      fromEmail: "noreply@berrytap.com",
      replyToEmail: "support@berrytap.com",
      rateLimit: "100 emails/hour",
    },
  },
  {
    id: "sms",
    name: "SMS",
    icon: "📱",
    type: "sms",
    connected: true,
    active: true,
    provider: "Twilio",
    status: "healthy",
    sentToday: 89,
    failedToday: 0,
    deliveryRate: 100,
    lastTested: {
      date: "1 day ago",
      by: "Sarah J.",
      result: "success",
    },
  },
  {
    id: "whatsapp",
    name: "WhatsApp",
    icon: "💬",
    type: "whatsapp",
    connected: false,
    active: false,
    provider: "Twilio",
    status: "setup-required",
    sentToday: 0,
    failedToday: 0,
    deliveryRate: 0,
  },
  {
    id: "push",
    name: "Push Notifications",
    icon: "🔔",
    type: "push",
    connected: true,
    active: true,
    provider: "Firebase",
    status: "healthy",
    sentToday: 67,
    failedToday: 1,
    deliveryRate: 98.5,
    lastTested: {
      date: "3 hours ago",
      by: "Michael C.",
      result: "success",
    },
  },
  {
    id: "in-app",
    name: "In-App Notifications",
    icon: "📲",
    type: "in-app",
    connected: true,
    active: true,
    provider: "Built-in",
    status: "healthy",
    sentToday: 201,
    failedToday: 0,
    deliveryRate: 100,
    lastTested: {
      date: "1 hour ago",
      by: "System",
      result: "success",
    },
  },
  {
    id: "receipt",
    name: "Receipt Email",
    icon: "📨",
    type: "receipt",
    connected: true,
    active: true,
    provider: "SendGrid",
    status: "healthy",
    sentToday: 134,
    failedToday: 1,
    deliveryRate: 99.3,
    lastTested: {
      date: "2 hours ago",
      by: "Sarah J.",
      result: "success",
    },
  },
]

export const mockTemplates: NotificationTemplate[] = [
  {
    id: "1",
    name: "Order Confirmed",
    description: "Sent when order placed",
    type: "order",
    channels: ["email", "sms", "push"],
    active: true,
    sentLast7Days: 89,
    updatedAt: "Nov 10, 2024",
    updatedBy: "Sarah Johnson",
    subject: "Your order {{order_number}} is confirmed! 🎉",
    content: "Hi {{customer_name}}, thank you for your order...",
  },
  {
    id: "2",
    name: "Order Ready",
    description: "Sent when order ready",
    type: "order",
    channels: ["email", "sms", "whatsapp", "push"],
    active: true,
    sentLast7Days: 134,
    updatedAt: "Nov 8, 2024",
    updatedBy: "Michael Chen",
    subject: "Your order is ready for pickup!",
    content: "Hi {{customer_name}}, your order {{order_number}} is ready...",
  },
  {
    id: "3",
    name: "Reservation Confirmed",
    description: "Sent after booking",
    type: "reservation",
    channels: ["email", "sms"],
    active: true,
    sentLast7Days: 56,
    updatedAt: "Nov 15, 2024",
    updatedBy: "Sarah Johnson",
    subject: "Reservation confirmed for {{reservation_date}}",
    content: "Hi {{customer_name}}, your reservation is confirmed...",
  },
  {
    id: "4",
    name: "Reservation Reminder",
    description: "Sent 2 hours before",
    type: "reservation",
    channels: ["email", "sms", "whatsapp"],
    active: true,
    sentLast7Days: 43,
    updatedAt: "Nov 12, 2024",
    updatedBy: "Michael Chen",
    subject: "Reminder: Your reservation is today at {{time}}",
    content: "Hi {{customer_name}}, just a reminder...",
  },
  {
    id: "5",
    name: "Order Receipt",
    description: "Email receipt with PDF",
    type: "receipt",
    channels: ["email"],
    active: true,
    sentLast7Days: 892,
    updatedAt: "Oct 28, 2024",
    updatedBy: "Sarah Johnson",
    subject: "Receipt for order {{order_number}}",
    content: "Thank you for your purchase...",
  },
  {
    id: "6",
    name: "Low Stock Alert",
    description: "Sent to staff",
    type: "inventory",
    channels: ["email", "push"],
    active: true,
    sentLast7Days: 12,
    updatedAt: "Nov 5, 2024",
    updatedBy: "Michael Chen",
    subject: "Low stock alert: {{item_name}}",
    content: "Item {{item_name}} is running low...",
  },
]

export const mockTriggers: NotificationTrigger[] = [
  {
    id: "1",
    event: 'When order.status changes to "confirmed"',
    template: "Order Confirmed",
    channels: ["email", "sms", "push"],
    active: true,
    sentLast7Days: 89,
    successRate: 98.9,
  },
  {
    id: "2",
    event: 'When order.status changes to "ready"',
    template: "Order Ready",
    channels: ["email", "sms", "whatsapp", "push"],
    active: true,
    sentLast7Days: 134,
    successRate: 99.2,
  },
  {
    id: "3",
    event: "When reservation.created",
    template: "Reservation Confirmed",
    channels: ["email", "sms"],
    active: true,
    sentLast7Days: 56,
    successRate: 100,
  },
  {
    id: "4",
    event: "When reservation.time is 2 hours before start",
    template: "Reservation Reminder",
    channels: ["email", "sms", "whatsapp"],
    active: true,
    sentLast7Days: 43,
    successRate: 97.7,
  },
  {
    id: "5",
    event: "When inventory.quantity < threshold",
    template: "Low Stock Alert",
    channels: ["email", "push"],
    active: false,
    sentLast7Days: 12,
    successRate: 100,
  },
]

export const mockDeliveryLogs: DeliveryLog[] = [
  {
    id: "1",
    type: "Order Ready",
    recipient: {
      name: "John Smith",
      email: "john@email.com",
      phone: "+356 9123 4567",
    },
    channels: [
      { type: "email", status: "delivered", sentAt: "2:45 PM", deliveredAt: "2:45 PM" },
      { type: "sms", status: "delivered", sentAt: "2:45 PM", deliveredAt: "2:45 PM" },
      { type: "push", status: "delivered", sentAt: "2:45 PM", deliveredAt: "2:45 PM" },
    ],
    createdAt: "2:45 PM Nov 21",
    relatedOrder: "#ORD-12345",
    relatedLocation: "Valletta Main",
  },
  {
    id: "2",
    type: "Order Confirmed",
    recipient: {
      name: "Sarah Test",
      email: "sarah@test.com",
      phone: "+356 9876 5432",
    },
    channels: [
      { type: "email", status: "delivered", sentAt: "2:30 PM", deliveredAt: "2:30 PM" },
      { type: "sms", status: "delivered", sentAt: "2:30 PM", deliveredAt: "2:30 PM" },
    ],
    createdAt: "2:30 PM Nov 21",
    relatedOrder: "#ORD-12344",
  },
  {
    id: "3",
    type: "Reservation Confirmed",
    recipient: {
      name: "Mike Johnson",
      email: "mike@email.com",
    },
    channels: [{ type: "email", status: "failed", error: "Invalid address (550)" }],
    createdAt: "2:15 PM Nov 21",
  },
  {
    id: "4",
    type: "Order Ready",
    recipient: {
      name: "Anna Smith",
      email: "anna@email.com",
      phone: "+356 2123 4567",
    },
    channels: [
      { type: "email", status: "delivered", sentAt: "1:45 PM", deliveredAt: "1:45 PM" },
      { type: "sms", status: "pending" },
    ],
    createdAt: "1:45 PM Nov 21",
  },
]
