export const mockTemplatesData = {
  templates: [
    {
      id: "tpl_001",
      name: "Welcome Email",
      channels: ["email"],
      category: "welcome",
      subjectLine: "Welcome! Here's 20% off your first visit",
      preview:
        "Welcome to BerryTap! We're thrilled to have you. As a special welcome gift, here's 20% off your first visit!",
      rating: 4.8,
      usageCount: 24,
      avgMetrics: {
        openRate: 42.3,
        ctr: 8.7,
        conversions: 12.6,
      },
      variables: ["{{firstName}}", "{{lastName}}", "{{promoCode}}", "{{expiryDate}}", "{{companyName}}"],
      createdAt: "2024-11-01",
      createdBy: "Sarah Johnson",
      lastUsed: "2 days ago",
      lastModified: "2024-11-10",
      owner: "team",
      status: "published",
    },
    {
      id: "tpl_002",
      name: "20% Off Promo",
      channels: ["email", "sms"],
      category: "promotional",
      subjectLine: "Flash Sale: 20% off everything today!",
      preview: "Don't miss out! Get 20% off your entire order today only. Use code FLASH20 at checkout.",
      rating: 4.6,
      usageCount: 156,
      avgMetrics: {
        openRate: 38.2,
        ctr: 11.4,
        conversions: 15.2,
      },
      variables: ["{{firstName}}", "{{promoCode}}", "{{expiryDate}}"],
      createdAt: "2024-10-15",
      createdBy: "Marketing Team",
      lastUsed: "1 day ago",
      owner: "team",
      status: "published",
    },
    {
      id: "tpl_003",
      name: "Win-Back Series",
      channels: ["email"],
      category: "win_back",
      subjectLine: "We miss you! Come back for 25% off",
      preview:
        "It's been a while since your last visit. We'd love to see you again! Here's 25% off to welcome you back.",
      rating: 4.9,
      usageCount: 12,
      avgMetrics: {
        openRate: 35.8,
        ctr: 6.2,
        conversions: 8.9,
      },
      variables: ["{{firstName}}", "{{lastVisitDate}}", "{{promoCode}}", "{{favoriteItem}}"],
      createdAt: "2024-11-10",
      createdBy: "You",
      lastUsed: "5 days ago",
      owner: "my_templates",
      status: "published",
    },
    {
      id: "tpl_004",
      name: "Birthday Special",
      channels: ["email", "sms", "in_app"],
      category: "birthday",
      subjectLine: "Happy Birthday! Enjoy a free dessert on us",
      preview: "Happy birthday! Celebrate with us and get a free dessert with any meal purchase.",
      rating: 5.0,
      usageCount: 89,
      avgMetrics: {
        openRate: 45.6,
        ctr: 14.2,
        conversions: 22.8,
      },
      variables: ["{{firstName}}", "{{birthday}}", "{{promoCode}}"],
      createdAt: "2024-09-20",
      createdBy: "Marketing Team",
      lastUsed: "Today",
      owner: "team",
      status: "published",
    },
    {
      id: "tpl_005",
      name: "Flash Sale Alert",
      channels: ["sms"],
      category: "promotional",
      subjectLine: "",
      preview: "FLASH SALE! 30% off for the next 2 hours. Show this text at checkout. Valid until 8PM.",
      rating: 4.7,
      usageCount: 234,
      avgMetrics: {
        ctr: 12.3,
        conversions: 18.4,
      },
      variables: ["{{promoCode}}", "{{expiryTime}}"],
      createdAt: "2024-11-05",
      createdBy: "Sarah Johnson",
      lastUsed: "Yesterday",
      owner: "team",
      status: "published",
    },
    {
      id: "tpl_006",
      name: "New Menu Item",
      channels: ["email"],
      category: "announcement",
      subjectLine: "Introducing our new signature burger!",
      preview:
        "We're excited to introduce our new signature burger! Made with locally sourced ingredients and our secret sauce.",
      rating: 4.5,
      usageCount: 45,
      avgMetrics: {
        openRate: 40.2,
        ctr: 9.8,
        conversions: 11.5,
      },
      variables: ["{{firstName}}", "{{itemName}}", "{{itemPrice}}", "{{itemImage}}"],
      createdAt: "2024-10-28",
      createdBy: "Marketing Team",
      lastUsed: "1 week ago",
      owner: "team",
      status: "published",
    },
    {
      id: "tpl_007",
      name: "Reservation Confirmation",
      channels: ["email", "sms"],
      category: "transactional",
      subjectLine: "Your reservation is confirmed",
      preview: "Your reservation at BerryTap is confirmed. We look forward to seeing you!",
      rating: 4.9,
      usageCount: 567,
      avgMetrics: {
        openRate: 92.5,
        ctr: 15.2,
      },
      variables: [
        "{{firstName}}",
        "{{reservationDate}}",
        "{{reservationTime}}",
        "{{partySize}}",
        "{{confirmationCode}}",
      ],
      createdAt: "2024-08-15",
      createdBy: "System",
      lastUsed: "Today",
      owner: "system",
      status: "published",
    },
    {
      id: "tpl_008",
      name: "Loyalty Points Earned",
      channels: ["email", "in_app"],
      category: "transactional",
      subjectLine: "You earned 50 points!",
      preview: "Great news! You just earned 50 points from your recent visit. Your new balance is 450 points.",
      rating: 4.8,
      usageCount: 892,
      avgMetrics: {
        openRate: 65.3,
        ctr: 18.7,
      },
      variables: ["{{firstName}}", "{{pointsEarned}}", "{{pointsBalance}}", "{{nextReward}}"],
      createdAt: "2024-09-01",
      createdBy: "System",
      lastUsed: "Today",
      owner: "system",
      status: "published",
    },
    {
      id: "tpl_009",
      name: "Holiday Special",
      channels: ["email", "sms"],
      category: "seasonal",
      subjectLine: "Holiday menu is here! Book your table now",
      preview: "Our special holiday menu is available! Reserve your table now for an unforgettable dining experience.",
      rating: 4.7,
      usageCount: 78,
      avgMetrics: {
        openRate: 44.8,
        ctr: 12.3,
        conversions: 16.7,
      },
      variables: ["{{firstName}}", "{{holidayName}}", "{{menuLink}}", "{{bookingLink}}"],
      createdAt: "2024-11-15",
      createdBy: "Marketing Team",
      lastUsed: "3 days ago",
      owner: "team",
      status: "published",
    },
    {
      id: "tpl_010",
      name: "VIP Exclusive Offer",
      channels: ["email"],
      category: "promotional",
      subjectLine: "VIP Exclusive: Early access to our new menu",
      preview: "As one of our valued VIP members, you get exclusive early access to try our new seasonal menu.",
      rating: 4.9,
      usageCount: 34,
      avgMetrics: {
        openRate: 52.3,
        ctr: 16.8,
        conversions: 24.5,
      },
      variables: ["{{firstName}}", "{{vipTier}}", "{{exclusiveDate}}", "{{bookingLink}}"],
      createdAt: "2024-10-20",
      createdBy: "You",
      lastUsed: "1 week ago",
      owner: "my_templates",
      status: "published",
    },
    {
      id: "tpl_011",
      name: "Weekly Newsletter",
      channels: ["email"],
      category: "announcement",
      subjectLine: "This week at BerryTap: Events, specials & more",
      preview: "Check out what's happening this week at BerryTap! Live music, chef specials, and happy hour deals.",
      rating: 4.3,
      usageCount: 156,
      avgMetrics: {
        openRate: 32.5,
        ctr: 7.8,
      },
      variables: ["{{firstName}}", "{{weekDates}}", "{{events}}", "{{specials}}"],
      createdAt: "2024-09-10",
      createdBy: "Marketing Team",
      lastUsed: "Today",
      owner: "team",
      status: "published",
    },
    {
      id: "tpl_012",
      name: "Feedback Request",
      channels: ["email", "sms"],
      category: "transactional",
      subjectLine: "How was your visit?",
      preview: "We'd love to hear about your recent experience at BerryTap. Your feedback helps us improve!",
      rating: 4.6,
      usageCount: 445,
      avgMetrics: {
        openRate: 38.9,
        ctr: 22.4,
      },
      variables: ["{{firstName}}", "{{visitDate}}", "{{surveyLink}}"],
      createdAt: "2024-08-25",
      createdBy: "System",
      lastUsed: "Today",
      owner: "system",
      status: "published",
    },
    {
      id: "tpl_013",
      name: "Order Ready",
      channels: ["sms", "in_app"],
      category: "transactional",
      subjectLine: "",
      preview: "Your order #{{orderNumber}} is ready for pickup! Please come to the counter.",
      rating: 4.9,
      usageCount: 1234,
      avgMetrics: {
        ctr: 95.2,
      },
      variables: ["{{orderNumber}}", "{{estimatedWait}}"],
      createdAt: "2024-07-15",
      createdBy: "System",
      lastUsed: "Today",
      owner: "system",
      status: "published",
    },
    {
      id: "tpl_014",
      name: "Last Chance Offer",
      channels: ["email", "sms"],
      category: "promotional",
      subjectLine: "Last chance! Offer expires tonight",
      preview: "Don't miss out! Your exclusive 30% off offer expires tonight at midnight. Order now!",
      rating: 4.8,
      usageCount: 67,
      avgMetrics: {
        openRate: 41.7,
        ctr: 13.9,
        conversions: 19.3,
      },
      variables: ["{{firstName}}", "{{promoCode}}", "{{expiryTime}}"],
      createdAt: "2024-10-30",
      createdBy: "Marketing Team",
      lastUsed: "2 days ago",
      owner: "team",
      status: "published",
    },
    {
      id: "tpl_015",
      name: "Refer a Friend",
      channels: ["email", "in_app"],
      category: "promotional",
      subjectLine: "Give €10, Get €10 when you refer friends",
      preview: "Love BerryTap? Share the love! Refer a friend and you'll both get €10 off your next order.",
      rating: 4.5,
      usageCount: 98,
      avgMetrics: {
        openRate: 36.4,
        ctr: 10.2,
        conversions: 8.5,
      },
      variables: ["{{firstName}}", "{{referralCode}}", "{{referralLink}}"],
      createdAt: "2024-09-05",
      createdBy: "Marketing Team",
      lastUsed: "4 days ago",
      owner: "team",
      status: "published",
    },
    {
      id: "tpl_016",
      name: "Draft - Summer Campaign",
      channels: ["email"],
      category: "seasonal",
      subjectLine: "Summer is here! Try our new refreshing menu",
      preview: "Beat the heat with our new summer menu featuring fresh salads, cold drinks, and light bites.",
      rating: 0,
      usageCount: 0,
      variables: ["{{firstName}}", "{{menuLink}}"],
      createdAt: "2024-11-18",
      createdBy: "You",
      owner: "my_templates",
      status: "draft",
    },
  ],
  categoryCounts: {
    all: 16,
    welcome: 1,
    promotional: 6,
    win_back: 1,
    announcement: 3,
    seasonal: 2,
    birthday: 1,
    transactional: 5,
  },
}
