export const mockActivityData = {
  activities: [
    {
      id: "act_001",
      type: "created",
      userName: "Sarah Johnson",
      userInitials: "SJ",
      campaignName: "Weekend Brunch Special",
      description: "created campaign",
      timestamp: "2024-11-20T15:45:00Z",
      details: null,
      comment: null,
    },
    {
      id: "act_002",
      type: "submitted",
      userName: "Sarah Johnson",
      userInitials: "SJ",
      campaignName: "Weekend Brunch Special",
      description: "submitted for approval",
      timestamp: "2024-11-20T15:46:00Z",
      details: ["Approver: Marketing Manager", "Status: Pending"],
      comment: null,
    },
    {
      id: "act_003",
      type: "approved",
      userName: "Marketing Director",
      userInitials: "MD",
      campaignName: "Flash Sale - 48 Hour Promo",
      description: "approved campaign",
      timestamp: "2024-11-20T13:45:00Z",
      details: null,
      comment: "Approved. Good timing for weekend traffic",
    },
    {
      id: "act_004",
      type: "sent",
      userName: "System",
      userInitials: "SY",
      campaignName: "Flash Sale - 48 Hour Promo",
      description: "sent campaign",
      timestamp: "2024-11-20T08:00:00Z",
      details: ["Recipients: 5,678", "Channels: Email + SMS"],
      comment: null,
    },
    {
      id: "act_005",
      type: "duplicated",
      userName: "Michael Chen",
      userInitials: "MC",
      campaignName: "Flash Sale - 48 Hour Promo",
      description: "duplicated campaign",
      timestamp: "2024-11-19T16:30:00Z",
      details: ['New campaign: "Flash Sale - 48 Hour Promo (Copy)"'],
      comment: null,
    },
    {
      id: "act_006",
      type: "archived",
      userName: "Sarah Johnson",
      userInitials: "SJ",
      campaignName: "October Flash Sale",
      description: "archived campaign",
      timestamp: "2024-11-18T14:15:00Z",
      details: null,
      comment: null,
    },
    {
      id: "act_007",
      type: "sent",
      userName: "System",
      userInitials: "SY",
      campaignName: "Welcome Series - New Customers",
      description: "sent campaign",
      timestamp: "2024-11-15T09:00:00Z",
      details: ["Recipients: 1,234", "Channels: Email + SMS", "Performance: 42.3% open • €8,900 revenue"],
      comment: null,
    },
    {
      id: "act_008",
      type: "approved",
      userName: "Marketing Manager",
      userInitials: "MM",
      campaignName: "Welcome Series - New Customers",
      description: "approved campaign",
      timestamp: "2024-11-15T08:30:00Z",
      details: null,
      comment: "Looks good, approved for sending",
    },
    {
      id: "act_009",
      type: "created",
      userName: "Lisa Park",
      userInitials: "LP",
      campaignName: "Holiday Season Kickoff",
      description: "created campaign",
      timestamp: "2024-11-14T10:00:00Z",
      details: null,
      comment: null,
    },
    {
      id: "act_010",
      type: "sent",
      userName: "System",
      userInitials: "SY",
      campaignName: "Event RSVP Reminder",
      description: "sent campaign",
      timestamp: "2024-11-14T16:00:00Z",
      details: ["Recipients: 567", "Channels: Email + SMS", "Performance: 60.8% open"],
      comment: null,
    },
  ],
}
