export const mockCampaignsData = {
  kpis: {
    totalSent: 24567,
    totalSentChange: 12,
    avgOpenRate: 32.4,
    avgOpenRateChange: 2.3,
    totalConversions: 1234,
    totalConversionsChange: 156,
    totalRevenue: 45678,
    totalRevenueChange: 5234,
  },
  campaigns: [
    {
      id: "camp_001",
      name: "Welcome Series - New Customers",
      channels: ["email", "sms"],
      status: "sent",
      audience: { segmentName: "New Customers (Last 7 Days)", count: 1234 },
      sentAt: "2024-11-15T09:00:00Z",
      createdBy: "Sarah Johnson",
      metrics: {
        sent: 1234,
        delivered: 1215,
        deliveryRate: 98.5,
        opens: 514,
        openRate: 42.3,
        clicks: 106,
        clickRate: 8.7,
        conversions: 156,
        conversionRate: 12.6,
        revenue: 12345,
        roi: 4.2,
        unsubscribes: 3,
      },
    },
    {
      id: "camp_002",
      name: "Lapsed Customer Win-Back",
      channels: ["email", "whatsapp"],
      status: "scheduled",
      audience: { segmentName: "Lapsed 30-90 Days", count: 892 },
      schedule: { sendAt: "2024-11-22T10:00:00Z", timezone: "Europe/Malta" },
      createdBy: "Michael Chen",
      estimatedCost: 178,
    },
    {
      id: "camp_003",
      name: "Flash Sale - 48 Hour Promo",
      channels: ["email", "sms", "in_app"],
      status: "sending",
      audience: { segmentName: "All Active Members", count: 5678 },
      startedAt: "2024-11-20T08:00:00Z",
      createdBy: "Lisa Park",
      progress: {
        sent: 2845,
        total: 5678,
        percentage: 50.1,
        estimatedCompletion: "15 minutes",
      },
    },
    {
      id: "camp_004",
      name: "Weekend Brunch Special",
      channels: ["sms"],
      status: "failed",
      audience: { segmentName: "Weekend Warriors", count: 3456 },
      failedAt: "2024-11-18T07:00:00Z",
      createdBy: "Sarah Johnson",
      error: {
        message: "SMS provider rate limit exceeded",
        partialSent: 234,
        partialTotal: 3456,
        code: "RATE_LIMIT",
      },
    },
    {
      id: "camp_005",
      name: "Holiday Season Kickoff",
      channels: ["email"],
      status: "draft",
      lastEditedAt: "2024-11-19T14:30:00Z",
      audience: { segmentName: "All Subscribers", count: 8901 },
      createdBy: "Michael Chen",
      completionStatus: {
        setup: true,
        audience: true,
        message: false,
        schedule: false,
      },
    },
    {
      id: "camp_006",
      name: "Birthday Rewards Campaign",
      channels: ["email", "in_app"],
      status: "sent",
      audience: { segmentName: "Birthday This Month", count: 456 },
      sentAt: "2024-11-01T08:00:00Z",
      createdBy: "Lisa Park",
      metrics: {
        sent: 456,
        delivered: 445,
        deliveryRate: 97.6,
        opens: 234,
        openRate: 51.2,
        clicks: 89,
        clickRate: 19.5,
        conversions: 67,
        conversionRate: 14.7,
        revenue: 5678,
        roi: 8.9,
        unsubscribes: 2,
      },
    },
    {
      id: "camp_007",
      name: "VIP Exclusive Preview",
      channels: ["email", "whatsapp"],
      status: "sent",
      audience: { segmentName: "VIP Customers", count: 234 },
      sentAt: "2024-11-12T16:00:00Z",
      createdBy: "Sarah Johnson",
      metrics: {
        sent: 234,
        delivered: 232,
        deliveryRate: 99.1,
        opens: 189,
        openRate: 80.8,
        clicks: 123,
        clickRate: 52.6,
        conversions: 89,
        conversionRate: 38.0,
        revenue: 23456,
        roi: 12.3,
        unsubscribes: 0,
      },
    },
    {
      id: "camp_008",
      name: "Lunch Special Reminder",
      channels: ["sms", "in_app"],
      status: "scheduled",
      audience: { segmentName: "Lunch Regulars", count: 1567 },
      schedule: { sendAt: "2024-11-21T11:00:00Z", timezone: "Europe/Malta" },
      createdBy: "Michael Chen",
      estimatedCost: 94,
    },
    {
      id: "camp_009",
      name: "Feedback Request - Recent Visitors",
      channels: ["email"],
      status: "sent",
      audience: { segmentName: "Visited Last 7 Days", count: 2345 },
      sentAt: "2024-11-16T14:00:00Z",
      createdBy: "Lisa Park",
      metrics: {
        sent: 2345,
        delivered: 2301,
        deliveryRate: 98.1,
        opens: 678,
        openRate: 28.9,
        clicks: 234,
        clickRate: 10.0,
        conversions: 45,
        conversionRate: 1.9,
        revenue: 0,
        roi: 0,
        unsubscribes: 12,
      },
    },
    {
      id: "camp_010",
      name: "Re-engagement Series Part 1",
      channels: ["email", "sms"],
      status: "sent",
      audience: { segmentName: "Inactive 60+ Days", count: 3456 },
      sentAt: "2024-11-10T10:00:00Z",
      createdBy: "Sarah Johnson",
      metrics: {
        sent: 3456,
        delivered: 3389,
        deliveryRate: 98.1,
        opens: 892,
        openRate: 25.8,
        clicks: 234,
        clickRate: 6.8,
        conversions: 78,
        conversionRate: 2.3,
        revenue: 4567,
        roi: 2.1,
        unsubscribes: 45,
      },
    },
    {
      id: "camp_011",
      name: "New Menu Item Launch",
      channels: ["email", "in_app", "receipt"],
      status: "scheduled",
      audience: { segmentName: "All Active Members", count: 7890 },
      schedule: { sendAt: "2024-11-25T09:00:00Z", timezone: "Europe/Malta" },
      createdBy: "Lisa Park",
      estimatedCost: 0,
    },
    {
      id: "camp_012",
      name: "Happy Hour Promotion",
      channels: ["sms", "whatsapp"],
      status: "paused",
      audience: { segmentName: "Happy Hour Segment", count: 2567 },
      lastEditedAt: "2024-11-17T15:30:00Z",
      createdBy: "Michael Chen",
      estimatedCost: 154,
    },
    {
      id: "camp_013",
      name: "Loyalty Program Reminder",
      channels: ["email"],
      status: "sent",
      audience: { segmentName: "Loyalty Members", count: 4567 },
      sentAt: "2024-11-08T09:00:00Z",
      createdBy: "Sarah Johnson",
      metrics: {
        sent: 4567,
        delivered: 4478,
        deliveryRate: 98.1,
        opens: 1567,
        openRate: 34.3,
        clicks: 456,
        clickRate: 10.0,
        conversions: 189,
        conversionRate: 4.1,
        revenue: 8901,
        roi: 3.4,
        unsubscribes: 23,
      },
    },
    {
      id: "camp_014",
      name: "Event RSVP Reminder",
      channels: ["email", "sms"],
      status: "sent",
      audience: { segmentName: "Event Invitees", count: 567 },
      sentAt: "2024-11-14T16:00:00Z",
      createdBy: "Lisa Park",
      metrics: {
        sent: 567,
        delivered: 556,
        deliveryRate: 98.1,
        opens: 345,
        openRate: 60.8,
        clicks: 234,
        clickRate: 41.3,
        conversions: 123,
        conversionRate: 21.7,
        revenue: 0,
        roi: 0,
        unsubscribes: 3,
      },
    },
    {
      id: "camp_015",
      name: "Seasonal Menu Tease",
      channels: ["email", "in_app"],
      status: "draft",
      lastEditedAt: "2024-11-18T11:00:00Z",
      audience: { segmentName: "All Subscribers", count: 8901 },
      createdBy: "Michael Chen",
      completionStatus: {
        setup: true,
        audience: true,
        message: true,
        schedule: false,
      },
    },
    {
      id: "camp_016",
      name: "Customer Appreciation Day",
      channels: ["email", "sms", "whatsapp"],
      status: "scheduled",
      audience: { segmentName: "Top 100 Customers", count: 100 },
      schedule: { sendAt: "2024-11-30T08:00:00Z", timezone: "Europe/Malta" },
      createdBy: "Sarah Johnson",
      estimatedCost: 20,
    },
    {
      id: "camp_017",
      name: "Catering Services Promotion",
      channels: ["email"],
      status: "sent",
      audience: { segmentName: "Business Customers", count: 234 },
      sentAt: "2024-11-05T10:00:00Z",
      createdBy: "Lisa Park",
      metrics: {
        sent: 234,
        delivered: 230,
        deliveryRate: 98.3,
        opens: 123,
        openRate: 52.6,
        clicks: 67,
        clickRate: 28.6,
        conversions: 23,
        conversionRate: 9.8,
        revenue: 15678,
        roi: 18.7,
        unsubscribes: 1,
      },
    },
    {
      id: "camp_018",
      name: "Weekend Breakfast Special",
      channels: ["sms", "in_app"],
      status: "failed",
      audience: { segmentName: "Breakfast Lovers", count: 1890 },
      failedAt: "2024-11-17T06:30:00Z",
      createdBy: "Michael Chen",
      error: {
        message: "Invalid message template",
        partialSent: 0,
        partialTotal: 1890,
        code: "TEMPLATE_ERROR",
      },
    },
    {
      id: "camp_019",
      name: "Refer a Friend Incentive",
      channels: ["email", "in_app"],
      status: "sent",
      audience: { segmentName: "Active Last 30 Days", count: 5678 },
      sentAt: "2024-11-13T12:00:00Z",
      createdBy: "Sarah Johnson",
      metrics: {
        sent: 5678,
        delivered: 5567,
        deliveryRate: 98.0,
        opens: 1890,
        openRate: 33.3,
        clicks: 567,
        clickRate: 10.0,
        conversions: 234,
        conversionRate: 4.1,
        revenue: 11234,
        roi: 5.6,
        unsubscribes: 34,
      },
    },
    {
      id: "camp_020",
      name: "Last Chance - Limited Offer",
      channels: ["email", "sms", "whatsapp", "in_app"],
      status: "scheduled",
      audience: { segmentName: "Engaged Subscribers", count: 6789 },
      schedule: { sendAt: "2024-11-24T18:00:00Z", timezone: "Europe/Malta" },
      createdBy: "Lisa Park",
      estimatedCost: 407,
    },
  ],
  segments: [
    { name: "New Customers (Last 7 Days)", count: 1234 },
    { name: "VIP Customers", count: 456 },
    { name: "Lapsed 30-90 Days", count: 892 },
    { name: "High Frequency Visitors", count: 2345 },
    { name: "Weekend Warriors", count: 1567 },
    { name: "All Active Members", count: 5678 },
  ],
}
