export const mockFoldersData = {
  folders: [
    {
      id: "root",
      name: "All Campaigns",
      campaignCount: 75,
      parentId: null,
      description: "All your campaigns",
      color: null,
    },
    {
      id: "q4_2024",
      name: "Q4 2024",
      campaignCount: 23,
      parentId: "root",
      description: "Q4 2024 promotional campaigns",
      color: "green",
    },
    {
      id: "nov_2024",
      name: "Nov 2024",
      campaignCount: 12,
      parentId: "q4_2024",
      description: null,
      color: null,
    },
    {
      id: "oct_2024",
      name: "Oct 2024",
      campaignCount: 8,
      parentId: "q4_2024",
      description: null,
      color: null,
    },
    {
      id: "dec_2024",
      name: "Dec 2024",
      campaignCount: 3,
      parentId: "q4_2024",
      description: null,
      color: null,
    },
    {
      id: "q3_2024",
      name: "Q3 2024",
      campaignCount: 28,
      parentId: "root",
      description: "Q3 2024 campaigns",
      color: "blue",
    },
    {
      id: "sep_2024",
      name: "Sep 2024",
      campaignCount: 10,
      parentId: "q3_2024",
      description: null,
      color: null,
    },
    {
      id: "aug_2024",
      name: "Aug 2024",
      campaignCount: 12,
      parentId: "q3_2024",
      description: null,
      color: null,
    },
    {
      id: "jul_2024",
      name: "Jul 2024",
      campaignCount: 6,
      parentId: "q3_2024",
      description: null,
      color: null,
    },
    {
      id: "templates",
      name: "Templates",
      campaignCount: 12,
      parentId: "root",
      description: "Reusable campaign templates",
      color: "purple",
    },
    {
      id: "ab_tests",
      name: "A/B Tests",
      campaignCount: 8,
      parentId: "root",
      description: "Active A/B test campaigns",
      color: "orange",
    },
    {
      id: "archived",
      name: "Archived",
      campaignCount: 24,
      parentId: "root",
      description: "Archived campaigns",
      color: "gray",
    },
  ],
  campaignsByFolder: {
    q4_2024: [
      {
        id: "camp_001",
        name: "Flash Sale - 48 Hour Promo",
        status: "sent",
        channels: ["email", "sms"],
        recipientCount: 5678,
        openRate: 48.2,
        sentAt: "2024-11-05T14:00:00Z",
      },
      {
        id: "camp_002",
        name: "Birthday Rewards (November)",
        status: "sent",
        channels: ["sms"],
        recipientCount: 3456,
        openRate: 45.8,
        sentAt: "2024-11-01T08:00:00Z",
      },
      {
        id: "camp_003",
        name: "Welcome Series - New Customers",
        status: "sent",
        channels: ["email", "sms"],
        recipientCount: 1234,
        openRate: 42.3,
        sentAt: "2024-11-15T09:00:00Z",
      },
    ],
  },
}
