import type {
  LegalDocument,
  RetentionPolicy,
  PrivacyRequest,
  ComplianceChecklist,
  AuditLogEntry,
  DocumentVersion,
} from "./types"

export const legalDocuments: LegalDocument[] = [
  {
    id: "doc_001",
    type: "privacy_policy",
    title: "Privacy Policy",
    version: "2.1",
    status: "active",
    uploadedDate: "2024-11-01",
    uploadedBy: "Sarah Johnson",
    effectiveDate: "2024-11-15",
    description: "Covers: Data collection, usage, sharing, retention, user rights",
    compliance: ["GDPR", "CCPA", "PIPEDA"],
    fileSize: "245 KB",
  },
  {
    id: "doc_002",
    type: "terms_of_service",
    title: "Terms of Service",
    version: "3.0",
    status: "active",
    uploadedDate: "2024-10-15",
    uploadedBy: "Michael Chen",
    effectiveDate: "2024-11-01",
    description: "Terms and conditions for using BerryTap services",
    compliance: ["General"],
    fileSize: "180 KB",
  },
  {
    id: "doc_003",
    type: "dpa",
    title: "Data Processing Agreement (DPA)",
    version: "1.2",
    status: "active",
    uploadedDate: "2024-09-01",
    uploadedBy: "Sarah Johnson",
    effectiveDate: "2024-09-01",
    validUntil: "2025-09-01",
    description: "Parties: BerryTap Ltd & Customer • Jurisdiction: EU/EEA",
    compliance: ["GDPR"],
    fileSize: "320 KB",
  },
  {
    id: "doc_004",
    type: "cookie_policy",
    title: "Cookie Policy",
    version: "1.0",
    status: "active",
    uploadedDate: "2024-08-01",
    uploadedBy: "Michael Chen",
    effectiveDate: "2024-08-15",
    description: "Cookie usage and consent management",
    compliance: ["GDPR", "ePrivacy"],
    fileSize: "95 KB",
  },
]

export const documentVersions: Record<string, DocumentVersion[]> = {
  doc_001: [
    {
      version: "2.1",
      uploadedDate: "2024-11-01",
      uploadedBy: "Sarah Johnson",
      effectiveDate: "2024-11-15",
      status: "active",
      changes: [
        "Updated data retention periods",
        "Added AI/ML processing disclosure",
        "Clarified international transfers",
      ],
    },
    {
      version: "2.0",
      uploadedDate: "2024-08-15",
      uploadedBy: "Michael Chen",
      effectiveDate: "2024-09-01",
      validUntil: "2024-11-14",
      status: "superseded",
      changes: ["CCPA compliance updates", "Cookie policy integration"],
    },
    {
      version: "1.5",
      uploadedDate: "2024-06-01",
      uploadedBy: "Sarah Johnson",
      effectiveDate: "2024-06-15",
      validUntil: "2024-08-31",
      status: "archived",
      changes: ["Initial GDPR compliance version"],
    },
  ],
}

export const retentionPolicies: RetentionPolicy[] = [
  {
    id: "ret_001",
    dataType: "customer_pii",
    displayName: "Customer PII",
    includes: "Names, emails, phone numbers, addresses",
    retentionPeriod: "7 years after last transaction",
    autoDelete: true,
    status: "active",
    lastReviewed: "2024-11-01",
    nextReview: "2025-02-01",
  },
  {
    id: "ret_002",
    dataType: "payment_data",
    displayName: "Payment Data",
    includes: "Card details, payment history",
    retentionPeriod: "10 years (PCI)",
    autoDelete: true,
    status: "active",
    lastReviewed: "2024-11-01",
    nextReview: "2025-02-01",
  },
  {
    id: "ret_003",
    dataType: "order_history",
    displayName: "Order History",
    includes: "Transaction records, order details",
    retentionPeriod: "5 years (tax law)",
    autoDelete: true,
    status: "active",
    lastReviewed: "2024-11-01",
    nextReview: "2025-02-01",
  },
  {
    id: "ret_004",
    dataType: "email_communications",
    displayName: "Email Communications",
    includes: "Customer correspondence",
    retentionPeriod: "3 years",
    autoDelete: true,
    status: "active",
    lastReviewed: "2024-11-01",
    nextReview: "2025-02-01",
  },
  {
    id: "ret_005",
    dataType: "analytics_data",
    displayName: "Analytics Data",
    includes: "Usage patterns, behavioral data",
    retentionPeriod: "2 years",
    autoDelete: true,
    status: "active",
    lastReviewed: "2024-11-01",
    nextReview: "2025-02-01",
  },
  {
    id: "ret_006",
    dataType: "audit_logs",
    displayName: "Audit Logs",
    includes: "System access logs, security events",
    retentionPeriod: "Indefinite",
    autoDelete: false,
    status: "active",
    lastReviewed: "2024-11-01",
    nextReview: "2025-02-01",
  },
]

export const privacyRequests: PrivacyRequest[] = [
  {
    id: "DSR-2024-0012",
    type: "data_export",
    requester: "John Smith",
    email: "john.smith@email.com",
    customerId: "cust_20231015_001",
    submittedDate: "2024-11-20T15:45:00",
    dueDate: "2024-12-05",
    status: "pending",
    legalBasis: "GDPR Article 15 (Right to access)",
    requestedData: ["All personal information", "Order history", "Communications"],
  },
  {
    id: "DSR-2024-0011",
    type: "data_deletion",
    requester: "Anna Jones",
    email: "anna.jones@email.com",
    customerId: "cust_20230820_045",
    submittedDate: "2024-11-19T10:30:00",
    dueDate: "2024-12-04",
    status: "pending",
    legalBasis: "GDPR Article 17 (Right to erasure)",
    warnings: ["Outstanding orders: 1 active order (€45.50)", "Account balance: €12.00 credit remaining"],
  },
  {
    id: "DSR-2024-0010",
    type: "data_export",
    requester: "Mike Wilson",
    email: "mike.wilson@email.com",
    customerId: "cust_20240115_078",
    submittedDate: "2024-11-15T14:15:00",
    dueDate: "2024-11-30",
    status: "completed",
    legalBasis: "GDPR Article 15",
    requestedData: ["Personal information", "Order history"],
  },
]

export const complianceChecklists: ComplianceChecklist[] = [
  {
    name: "GDPR Compliance",
    status: "complete",
    completedCount: 12,
    totalCount: 12,
    lastAudit: "2024-10-01",
    nextAudit: "2025-01-01",
    items: [
      { id: "gdpr_1", label: "Privacy policy published", completed: true },
      { id: "gdpr_2", label: "Consent management", completed: true },
      {
        id: "gdpr_3",
        label: "Data processing records",
        completed: true,
      },
      {
        id: "gdpr_4",
        label: "Breach notification process",
        completed: true,
      },
      {
        id: "gdpr_5",
        label: "Data protection officer assigned",
        completed: true,
      },
      { id: "gdpr_6", label: "Privacy by design", completed: true },
      { id: "gdpr_7", label: "Data retention policies", completed: true },
      { id: "gdpr_8", label: "Data portability", completed: true },
      {
        id: "gdpr_9",
        label: "Right to access implemented",
        completed: true,
      },
      { id: "gdpr_10", label: "Right to erasure", completed: true },
      {
        id: "gdpr_11",
        label: "Data processing agreements",
        completed: true,
      },
      { id: "gdpr_12", label: "International transfers", completed: true },
    ],
  },
  {
    name: "PCI DSS Compliance",
    status: "complete",
    completedCount: 6,
    totalCount: 6,
    certificate: {
      valid: true,
      validUntil: "2025-09-30",
      lastScan: "2024-11-15",
      nextScan: "2024-12-15",
    },
    items: [
      {
        id: "pci_1",
        label: "Secure network configuration",
        completed: true,
      },
      {
        id: "pci_2",
        label: "Vulnerability management",
        completed: true,
      },
      {
        id: "pci_3",
        label: "Cardholder data protection",
        completed: true,
      },
      { id: "pci_4", label: "Access control measures", completed: true },
      {
        id: "pci_5",
        label: "Data encryption at rest & transit",
        completed: true,
      },
      { id: "pci_6", label: "Security monitoring", completed: true },
    ],
  },
  {
    name: "CCPA Compliance",
    status: "complete",
    completedCount: 8,
    totalCount: 8,
    items: [
      {
        id: "ccpa_1",
        label: "Privacy notice at collection",
        completed: true,
      },
      { id: "ccpa_2", label: "Do Not Sell option", completed: true },
      { id: "ccpa_3", label: "Right to know implemented", completed: true },
      { id: "ccpa_4", label: "Right to delete", completed: true },
      {
        id: "ccpa_5",
        label: "Non-discrimination policy",
        completed: true,
      },
      {
        id: "ccpa_6",
        label: "Authorized agent process",
        completed: true,
      },
      {
        id: "ccpa_7",
        label: "Service provider agreements",
        completed: true,
      },
      {
        id: "ccpa_8",
        label: "Data breach notifications",
        completed: true,
      },
    ],
  },
]

export const auditLogs: AuditLogEntry[] = [
  {
    id: "aud_001",
    timestamp: "2024-11-21T14:30:00",
    action: "Approved export request",
    category: "Privacy Request",
    user: "Sarah Johnson",
    userRole: "Owner",
    details: "DSR-2024-0012 • john.smith@email",
    ipAddress: "185.23.45.67",
    location: "Valletta, Malta",
    relatedId: "DSR-2024-0012",
  },
  {
    id: "aud_002",
    timestamp: "2024-11-20T15:45:00",
    action: "Data export request received",
    category: "Privacy Request",
    user: "System",
    userRole: "System",
    details: "DSR-2024-0012 • john.smith@email",
    relatedId: "DSR-2024-0012",
  },
  {
    id: "aud_003",
    timestamp: "2024-11-19T10:30:00",
    action: "Data deletion request received",
    category: "Privacy Request",
    user: "System",
    userRole: "System",
    details: "DSR-2024-0011 • anna.jones@email",
    relatedId: "DSR-2024-0011",
  },
  {
    id: "aud_004",
    timestamp: "2024-11-15T16:20:00",
    action: "Export completed",
    category: "Privacy Request",
    user: "System",
    userRole: "System",
    details: "DSR-2024-0010 • mike.wilson@email",
    relatedId: "DSR-2024-0010",
  },
  {
    id: "aud_005",
    timestamp: "2024-11-01T11:00:00",
    action: "Updated privacy policy",
    category: "Document Management",
    user: "Sarah Johnson",
    userRole: "Owner",
    details: "Privacy Policy v2.1 • Effective: Nov 15",
    ipAddress: "185.23.45.67",
    relatedId: "doc_001",
  },
]
